### ISSUE TITLE
Unable to edit item with composite primary key

### ISSUE THREAD

**Issue by stiefdirckx** [TimGeyssens/UIOMatic#104]
I tried several configurations:
- `[PrimaryKey("Column1,Column2", autoIncrement = false)]` on class object
- `[PrimaryKeyColumn(AutoIncrement = false)]` on both property objects
- with and without autoincrement options

Expanding the tree or opening it in a list view works fine, but editing causes an exception: "Failed to get by id"

> at UIOMatic.Extensions.DatabaseExtensions.SingleOrDefault(Database db, Type type, Object primaryKey)
   at UIOMatic.Data.DefaultUIOMaticRepository.Get(String id)
   at UIOMatic.Services.PetaPocoObjectService.GetById(Type type, String id)

I tought Umbraco's PetaPoco implementation supported composite primary keys but does UI-O-Matic support it also? If so please point me to an example.

**Comment by TimGeyssens** [comment]
Hmm must say that that is an use case I haven't tested so probably it isn't supported... can you view the item? Just hitting the edit button fails?

**Comment by stiefdirckx** [comment]
Yup, the tree shows correctly but clicking an item causes the exception to pop up.

I also tried this, but it gave the same error:
https://our.umbraco.org/forum/developers/extending-umbraco/59672-Combined-primary-keys-with-petapoco

When I hover over an item in the tree I don't see an id or key in the generated URL.

**Comment by TimGeyssens** [comment]
Will have to see if this works with npoco now in v3

**Comment by TimGeyssens** [comment]
Appears there is some more info about it now https://our.umbraco.com/forum/developers/extending-umbraco/59672-Combined-primary-keys-with-petapoco#comment-315428

**Comment by TimGeyssens** [comment]
Hey, best thing would be to create a custom repo in this case... and handle the composite key stuff in there https://gist.github.com/TimGeyssens/cff7e3ea5a31849cc71407ba1b6b4886
