### ISSUE TITLE
Make field names human friendly by default

### ISSUE THREAD

**Issue by PeteDuncanson** [TimGeyssens/UIOMatic#105]
If the field has an accessor called FirstName (with that casing) why not automagically guess it should be "First Name" rather than requiring a label attribute on it. Would mean less attributes, less noise in most of the cases. Convention over configuration.

**Comment by mattbrailsford** [comment]
Great suggestion Pete :)

**Comment by TimGeyssens** [comment]
Made a small change to make this happen, if no name is set it will try to go to sentence case from pascal case... (coming up in v3.10.0)
