### ISSUE TITLE
Allow setting default sort column and direction for list view.

### ISSUE THREAD

**Issue by stiefdirckx** [TimGeyssens/UIOMatic#106]
When opening a list view for a table the records are sorted by default by the PK. It would be nice if you could override this by using a parameter on the `UIOMaticListViewField` attribute.

**Comment by TimGeyssens** [comment]
You can do this on your UIOMatic attribute if I remember correctly :)

**Comment by TimGeyssens** [comment]
You can for example 

`[UIOMatic("contactentries", "Contact Entries", "Contact Entry",
SortColumn = "Created", SortOrder = "desc", RenderType = UIOMaticRenderType.List)]`

**Comment by stiefdirckx** [comment]
Thanks, probably looked over it.
