### ISSUE TITLE
RenderType = UIOMaticRenderType.List seems to be broken in current nuget deploy

### ISSUE THREAD

**Issue by mistyn8** [TimGeyssens/UIOMatic#107]
I've just setup 7.5.7 umbraco via nuget, and then followed that with Install-Package Nibble.Umbraco.UIOMatic which installed 2.0.3

setting up the simple example.
```
[UIOMatic("people", "People", "Person", FolderIcon = "icon-users", ItemIcon = "icon-user", RenderType = UIOMaticRenderType.List)]
[TableName("People")]
public class Person
{
    [PrimaryKeyColumn(AutoIncrement = true)]
    public int Id { get; set; }

    [Required]
    [UIOMaticField(Name = "First name", Description = "Enter the persons first name")]
    public string FirstName { get; set; }

    [Required]
    [UIOMaticField(Name = "Last name", Description = "Enter the persons last name")]
    public string LastName { get; set; }

    [UIOMaticField(Name = "Picture", Description = "Select a picture", View = UIOMatic.Constants.FieldEditors.File)]
    public string Picture { get; set; }

    public override string ToString()
    {
        return FirstName + " " + LastName;
    }
```

I get an empty table... it seems to be the typeInfo api at fault as it returns an empty array for listViewProperties = [] at least that was as far as I got trying to resolve.

the full response from uioMaticObjectResource.getTypeInfo($scope.typeAlias, true)

`{"alias":"people","displayNamePlural":"People","displayNameSingular":"Person","name":"Person","tableName":"People","primaryKeyColumnName":"Id","autoIncrementPrimaryKey":true,"renderType":1,"rawProperties":[{"key":"Id","name":"Id","columnName":null,"type":"System.Int32","order":0},{"key":"FirstName","name":"FirstName","columnName":null,"type":"System.String","order":0},{"key":"LastName","name":"LastName","columnName":null,"type":"System.String","order":0},{"key":"Picture","name":"Picture","columnName":null,"type":"System.String","order":0}],"editableProperties":[{"tab":"General","tabOrder":0,"description":"Enter the persons first name","view":"/App_Plugins/UIOMatic/backoffice/views/fieldeditors/textfield.html","config":null,"key":"FirstName","name":"First name","columnName":"FirstName","type":"System.String","order":25},{"tab":"General","tabOrder":0,"description":"Enter the persons last name","view":"/App_Plugins/UIOMatic/backoffice/views/fieldeditors/textfield.html","config":null,"key":"LastName","name":"Last name","columnName":"LastName","type":"System.String","order":29},{"tab":"General","tabOrder":0,"description":"Select a picture","view":"/App_Plugins/UIOMatic/backoffice/views/fieldeditors/file.html","config":null,"key":"Picture","name":"Picture","columnName":"Picture","type":"System.String","order":32}],"listViewProperties":[],"listViewFilterProperties":[],"nameFieldKey":"","readOnly":false,"path":["-1","people"],"type":"Person, App_Code.nwjqf8kh, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","listViewActions":[],"sortColumn":null,"sortOrder":"ASC"}`

The same thing seems to be occuring for nested listviews too.

Any pointers much appreciated. :-)

**Comment by mistyn8** [comment]
stumbled on the answer.. decorate with [UIOMaticListViewField]

**Comment by TimGeyssens** [comment]
Ok be sure to check the latest docs over at http://uiomatic.readthedocs.io/en/stable/

**Comment by mistyn8** [comment]
I had read through those a few times and missed it completely... :-(

http://uiomatic.readthedocs.io/en/stable/04.Listview/ now I know what I'm looking for I did find it,
I think I got to "Now you won't see the items in the tree anymore but in a list view" and stopped reading.

Perhaps it might help others if there was a coded example for listview? ;-)

**Comment by TimGeyssens** [comment]
Ok good point, will update it a bit :)
