### ISSUE TITLE
[required]DateTime doesn't appear to be working

### ISSUE THREAD

**Issue by mistyn8** [TimGeyssens/UIOMatic#108]
```
 [Required]
 [Column("Date")]
 [UIOMaticField(Name = "Date", Description = "Enter the event date", View = UIOMatic.Constants.FieldEditors.Date)]
 [UIOMaticListViewField(Config = "{'format' : '{{value|date:format:short}}'}")]
 public DateTime Date { get; set; }
```

If I try to create/update with an empty date I get an ugly asp.net error in the sidepanel and not a nice client side notification?

>  Failed to update entity
> 
> Cannot insert the value NULL into column 'Date', table 'as_cpa_development_2016_12_01.dbo.CPAEvents'; column does not allow nulls. UPDATE fails.
>  The statement has been terminated.
> 
> EXCEPTION DETAILS:
> 
> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Date', table 'as_cpa_development_2016_12_01.dbo.CPAEvents'; column does not allow nulls. UPDATE fails.
>  The statement has been terminated.

**Comment by TimGeyssens** [comment]
Thanks for reporting I'll check it out!

**Comment by TimGeyssens** [comment]
Can you try with a nullable property?

**Comment by mistyn8** [comment]
Works if set to nullable though that's a little counter intuitive?

(sorry for the delay had to refactor some sections for date formating once a nullable)

**Comment by TimGeyssens** [comment]
Well some research seems to say that a Datetime always has a value so needs to be nullable for required to work ... http://stackoverflow.com/questions/27025004/how-can-i-make-a-datetime-model-property-required

**Comment by mistyn8** [comment]
hmmm interesting.. but then it fails inserting a null into the db? so it's got a null value at that point, perhaps some abstraction around minDate going on?

> For normal DateTimes, if you don't initialize them at all then they will match DateTime.MinValue, because it is a value type rather than a reference type.

**Comment by TimGeyssens** [comment]
Ok thanks for the details, will give it a go and see why it is failing

**Comment by mistyn8** [comment]
thanks to you have a working solution with the nullable type, so all's well with the world.

**Comment by TimGeyssens** [comment]
Awesome :)
