### ISSUE TITLE
Broken list view 2.0.3

### ISSUE THREAD

**Issue by AstuteMediaDev** [TimGeyssens/UIOMatic#110]
Sorry not sure if this is the place for bugs.

We have just upgraded to Uiomatic 2.0.3 + Umbraco 7.5.11.

List view has broken for us however tree view still functions correctly.

Our use case is very simple - we just have two attributed tables and list view has broken for both.

We can make do with tree view but any help fixing this would be much appreciated as it is a client site.

**Comment by TimGeyssens** [comment]
Ok will take a look, thanks for reporting!

**Comment by TimGeyssens** [comment]
Make sure to clear your browser cache just in case

**Comment by AstuteMediaDev** [comment]
Thanks Tim.

Clearing browser cache has no impact - always work with Chrome dev tools and cache disabled.

Records are visibly coming back in the list view - rows are showing but they are blank.

**Comment by TimGeyssens** [comment]
From which version did you upgrade UIOMatic?

**Comment by TimGeyssens** [comment]
If you are coming from v1 you need to explicitly mark the properties you want in the listview with the [UIOMaticListViewField] attribute

**Comment by AstuteMediaDev** [comment]
Prior version was 1.6 + Umbraco 7.5.3.

We  recently discovered two bugs in that version and decided to upgrade to fix them.

Bugs in that version:

1. Checkbox editor failed to save with  error:

/umbraco/backoffice/UIOMatic/Object/Validate (500 internal server error)
'input string was not in a correct format'

2. Changing pages caused error:

Uncaught Error: Syntax error, unrecognized expression: #/uiomatic/uioMaticTree/edit/Carsite.Umbraco.UIOMaticModels.UIOMaticVehicle ...

Although this didn't actually stop paging occurring.

**Comment by AstuteMediaDev** [comment]
Awesome thanks Tim that's fixed it 👍 

FYI we didn't see anything about this in the docs:

http://uiomatic.readthedocs.io/en/stable/

**Comment by TimGeyssens** [comment]
Did you check this page http://uiomatic.readthedocs.io/en/stable/04.Listview/

**Comment by AstuteMediaDev** [comment]
Doh :(

**Comment by mattbrailsford** [comment]
Sounds like you are missing the [UIOMaticListViewField] attribute on your
model properties http://uiomatic.readthedocs.io/en/stable/05.ListFieldViews/
