### ISSUE TITLE
Building a datatype to show some data based on the node id

### ISSUE THREAD

**Issue by rasmusfjord** [TimGeyssens/UIOMatic#112]
So I have an idea and would like to hear if its totally far fetched, if not how to get started.

So it would be a datatype, where you get the listview from UI O Matic though it would only show the entries which had the nodeid (in some petepoco property that you select on the settings page).

So an example whould be a node in umbraco is a "team" and all the members are petapoco entries, but a listview of the members and option to edit them directly on the node. 

Is it ´totally off?

We have a ton of experience in building datatypes, so its more to know if its totally an off idea.

**Comment by TimGeyssens** [comment]
Ow nice idea, yeah go for it :) makes sense...

**Comment by rasmusfjord** [comment]
Roger ill give it a shot, it would save us so much time getting this type.

**Comment by rasmusfjord** [comment]
Ill keep it open if any issues aries or ind the end their might be a PR :)

**Comment by TimGeyssens** [comment]
Awesome, if you need any pointers let us know :)

**Comment by rasmusfjord** [comment]
Hey Tim 

Im almost ready just need to create an edit/create dialog and im adding a few extra options to the datatype itself, one of these i would like to dicuss because it can easily be a bit off.

So im adding the following options to the new dataytpe :
hide create
hide search
hide delete
(custom SQL)

So the last one is the one i wanna discuss with you. My idea is that you dont want to delete a petapoco item on delete, but just set a flag, deleted:true, on the item. So my idea is to get around this, that you could have an extra field called custom SQL,, as a datatype option, so you could  write " Where Deleted = true". I know this is maybe not the pretties thing, but i dont see an option to go around it. What is your take, and do you maybe have a better idea.

**Comment by mattbrailsford** [comment]
Regarding the later option, I think we already have support for that
scenario (or if we don't, I do and I've not committed it) but you should
have the ability to set on your model a "Deleted" column option which uiom
uses to determine if an item is deleted.

We should shy away from custom sql in the pre value, instead, use the built
in repository support to define your own sql if you really need something
custom.

**Comment by rasmusfjord** [comment]
Hey Matt :) 

The deleted was just an example since we got 2-4 props that I wanna check upon depending on which listview datattype im creating, but yeah the custom sql was my last resort. 

Could you give an example on how to use the repo, couldnt find it in the docs? Just so i could see if it solved it.

**Comment by mattbrailsford** [comment]
Some info in the docs here
http://uiomatic.readthedocs.io/en/stable/12.Advanced/

**Comment by rasmusfjord** [comment]
Got it done :) 

Also got around the sql thing by adding predefined filters to the datatype 👍 

You mentioned you had made the thing so things didnt get deleted but just get flagged. I cant find it in the source code, so do you have it laying around ?:)

![image](https://cloud.githubusercontent.com/assets/1286043/24394085/dcf09060-139a-11e7-80e1-f6c55328f837.png)

**Comment by TimGeyssens** [comment]
Wow that looks amazing, great work!

**Comment by rasmusfjord** [comment]
Pr comming in a sec ;) if you can give me the solution to the delete issue i would be thrilled ;)

**Comment by TimGeyssens** [comment]
Hmm think @mattbrailsford knows that one best but I think if the DeletedColumnName property is set on the UIOMatic attribute it flags an object instead of deleting it https://github.com/TimGeyssens/UIOMatic/blob/v2/src/UIOMatic/Attributes/UIOMaticAttribute.cs

**Comment by TimGeyssens** [comment]
Small q is the property for nodeId setting mandatory, what happens if that isn't set? Just thinking it would make it even more useful if it isn't limited to filtering on node id by default (so you can drop a list view where you want)

**Comment by TimGeyssens** [comment]
@rasmusfjord for the delete stuff you can find all you need in this commit https://github.com/TimGeyssens/UIOMatic/commit/03ec0b89f56bf1a00adabf290dc1ea81d26569e4

**Comment by rasmusfjord** [comment]
ARH you guys rock :) ill get back on the Q in my PR :)

**Comment by rasmusfjord** [comment]
Hmm ive just checked the V2 branch, its true that its not part of the V2 right ?

**Comment by TimGeyssens** [comment]
Old issue, @rasmusfjord pr has been merged a while ago and part of v2 and now also v3
