### ISSUE TITLE
Bulk Select List Items

### ISSUE THREAD

**Issue by Nicholas-Westby** [TimGeyssens/UIOMatic#114]
Right now, if you want to select all of the displayed items, you must select each of them by clicking the checkboxes next to them:

![redirects-list](https://cloud.githubusercontent.com/assets/5933222/24431082/cf3d479a-13ce-11e7-8e22-8090ccaa9f81.png)

Would be nice if there were a checkbox above the list that allows for all of the items to be selected. That way, I could delete a bunch that got accidentally created.

**Comment by TimGeyssens** [comment]
Yeah would be nice :) PR away ;)

**Comment by TimGeyssens** [comment]
AH it's actually in there :)
