### ISSUE TITLE
Search doesn't work on tables containing Numreic columns

### ISSUE THREAD

**Issue by madsoulswe** [TimGeyssens/UIOMatic#115]
DefaultUIOMaticRepository.GetPaged uses LIKE on Numeric columns.

- If property is Numreic it should be ignored or cast the value before LIKE?

**Comment by TimGeyssens** [comment]
Good point, if you are up for it you can do a pull request :)

**Comment by TimGeyssens** [comment]
FIxed by pr #144 on v3
