### ISSUE TITLE
Default View Hyperlink/Button

### ISSUE THREAD

**Issue by Killerkiwi2005** [TimGeyssens/UIOMatic#116]
So this would be nice, to be able to do a generic button that opens a hyperlink

`[UIOMaticField(Name = "Publish",Description = "Publish Report", View =  UIOMatic.Constants.FieldEditors.Hyperlink, HRef = "/api/reports/generate/{{Value}}")]

public string ReportId { get; set; }`

**Comment by TimGeyssens** [comment]
Not sure I follow you on this one, mind describing a use case?

**Comment by TimGeyssens** [comment]
Ok so just a custom field view? That shows a link?
