### ISSUE TITLE
Show total items returned in list view.

### ISSUE THREAD

**Issue by harvzor** [TimGeyssens/UIOMatic#117]
I can see in the `/umbraco/backoffice/UIOMatic/Object/GetPaged` API call, the `totalItems` which match the current query are returned:

```
{
    "currentPage":1,
    "itemsPerPage":10,
    "totalPages":20,
    "totalItems":192,
    ...
}
```

I want to be able to see this in my view, so if I run a query, I can see how many results I have (rather than manually having to count).

**Comment by TimGeyssens** [comment]
Old issue, already fixed by pull request
