### ISSUE TITLE
Filtering doesn't work on non-database fields.

### ISSUE THREAD

**Issue by harvzor** [TimGeyssens/UIOMatic#119]
Creating a field on the POCO which does not exist in the database and attempting to filter/order by it causes an error.

The error appears to be because that field does not exist in the database and a SQL query is probably using the field: `System.Data.SqlClient.SqlException: Invalid column name 'NodeName'.`

In my specific example, I have stored an Umbraco node ID in the database. I want to display the name of that node to the user.

    [UIOMatic("nodes", "Nodes", "Nodes", RenderType = UIOMaticRenderType.List]
    [TableName("Nodes")]
    [ExplicitColumns]
    public class MovieTransaction
    {
        /// <summary>
        /// The ID of the Umbraco node.
        /// </summary>
        [UIOMaticField(Name = "Node ID", Description = "The ID of the Umbraco node.")]
        [UIOMaticListViewField]
        [UIOMaticListViewFilter]
        [Column("nodeId")]
        public int NodeId { get; set; }

        /// <summary>
        /// The name of the movie (gotten from the Umbraco node).
        /// </summary>
        [UIOMaticField(Name = "Node Name", Description = "The name of the Umbraco node.")]
        [UIOMaticListViewField]
        [UIOMaticListViewFilter] // Filter doesn't work because this data does not exist in the database.
        [Ignore]
        public string NodeName
        {
            get
            {
                var node = new UmbracoHelper(UmbracoContext.Current).TypedContent(MovieId);

                if (node != null)
                {
                    return node.Name;
                }

                return "Name not found.";
            }
        }
    }

An obvious work around would be to simply save the node name to the database too. However, do you have any other options?

Thanks!

**Comment by TimGeyssens** [comment]
Nope filtering happens on db level....

**Comment by TimGeyssens** [comment]
Wel you could replace the default repo with a custom implementation and then handle the getpaged data differently.... that's the only thing I can think of
