### ISSUE TITLE
FieldEditors.List

### ISSUE THREAD

**Issue by Killerkiwi2005** [TimGeyssens/UIOMatic#120]
I can't get this to work after looking over the documentation I just get an empty list

Any pointers? I must be missing some thing simple

```
[UIOMatic("ReportType", "Report Types", "Report Type", FolderIcon = "icon-list", ItemIcon = "icon-list",
    RenderType = UIOMaticRenderType.List, Order = 10)]
    [TableName("ReportType")]
    [PrimaryKey("Id", autoIncrement = true)]
    public class ReportType
    {
        public Guid Id { get; set; }

        [UIOMaticField(View = UIOMatic.Constants.FieldEditors.Textfield)]
        [UIOMaticListViewField]
        public string Name { get; set; }

        [UIOMaticField(View = UIOMatic.Constants.FieldEditors.List,
     Config = "{'typeAlias': 'ReportLabel', 'foreignKeyColumn' : 'ReportTypeId', 'canEdit' : true}")]
        public IEnumerable<ReportLabel> ReportLabel { get; set; }
    }

    [UIOMatic("ReportLabel", "Report Labels", "Report Label", FolderIcon = "icon-list", ItemIcon = "icon-list",
    RenderType = UIOMaticRenderType.List, Order = 11)]
    [TableName("ReportLabel")]
    [PrimaryKey("Id", autoIncrement = true)]
    public class ReportLabel
    {
        public Guid Id { get; set; }

        [UIOMaticField(View = UIOMatic.Constants.FieldEditors.Textfield)]
        [UIOMaticListViewField]
        public string Key { get; set; }

        [UIOMaticField(View = UIOMatic.Constants.FieldEditors.Textfield)]
        [UIOMaticListViewField]
        public string Value { get; set; }

        [UIOMaticListViewField]
        [UIOMaticField(Name = "Report Type",
            View = "dropdown",
            Config = "{typeAlias: 'ReportType', 'valueColumn': 'Id', 'sortColumn': 'Name', 'textTemplate' : '{{Name}}'}")]
        public Guid ReportTypeId { get; set; }
    }
```

**Comment by Killerkiwi2005** [comment]
Found the answer list.controller.js, note im using guid ids... the controller checks for a number...

` function fetchData() {
            if (!isNaN($scope.filterId)) { // Only fetch if we have an ID (ie, editing)
                uioMaticObjectResource.getPaged($scope.typeAlias, 1000, 1,
                    $scope.initialFetch ? "" : $scope.predicate,
                    $scope.initialFetch ? "" : ($scope.reverse ? "desc" : "asc"),
                    $scope.foreignKeyColumn + "|" + $scope.filterId,
                    "").then(function(resp) {
                    $scope.rows = resp.items;
                    $scope.initialFetch = false;
                });
            }
        }`

**Comment by TimGeyssens** [comment]
Ok thanks for the details

**Comment by uniquelau** [comment]
Ah! Thank-you for posting this, it's resolved an issue I've had whilst trying to display data from another table using a foreign key.

```
[Ignore]
[UIOMaticField(Name = "Notifications", Tab = "Notifications", View = "list",
            Config = "{'typeAlias' : 'Emails' , 'foreignKeyColumn' : 'InvoiceId', 'canEdit' : false}")]
public IEnumerable<Email> Emails { get; set; }
```

If you are looking for the file LemonTVnz mentions, it can be found here:

`/UIOMatic/backoffice/views/fieldeditors/list.controller.js`

If it helps someone else, I have changed the controller so we just check that string contains something...

```
if ($scope.filterId.length !== 0) { // Only fetch if we have something
// if (!isNaN($scope.filterId)) { // Only fetch if we have an ID (ie, editing)
```

**Comment by TimGeyssens** [comment]
Fixed in v3
