### ISSUE TITLE
Navigate from an ListViewAction to a create action

### ISSUE THREAD

**Issue by dtila** [TimGeyssens/UIOMatic#122]
Hi,

Is there a way to navigate from a ListViewAction to a create page where you can create a certain entity type ?

For example, I have a class A which can have B and C as a child, but I want to have the actions available only after I created the A class

**Comment by TimGeyssens** [comment]
Would this be something, on the edit page of class A you can then add actions... https://github.com/TimGeyssens/UIOMatic/issues/116

**Comment by TimGeyssens** [comment]
since version 3.1 there is a link view you can use... that would allow to have that extra custom link
