### ISSUE TITLE
Return undefined id after created new object

### ISSUE THREAD

**Issue by mrpeo** [TimGeyssens/UIOMatic#124]
When i save, it's not return the created id but return undefined --> errors.

See creenshot.

Please help!

Thank you!

![screenshot_4](https://user-images.githubusercontent.com/4709861/30288190-0a49cac8-9752-11e7-8584-481e4ae905df.jpg)

**Comment by mrpeo** [comment]
:( no one here

**Comment by TimGeyssens** [comment]
Mind sharing your poco?

**Comment by TimGeyssens** [comment]
Closing due to inactive...
