### ISSUE TITLE
UIOmatic proprety editor dropdown problem

### ISSUE THREAD

**Issue by mrflo** [TimGeyssens/UIOMatic#126]
Hi guys, 

I 've tried to use the dropdown list of a custom objects on Umbraco 7.6.1. When I am trying to select the "type of object" field, nothing appears in the value property. I can save it but in the content section nothing is saved. 
Do you have an idea what could be the issue? It seems that there is no call to the webservice like if the angular "watch" event is not working. 

Thanks for your help and for this plugin!!

MrFlo

![capture](https://user-images.githubusercontent.com/5419588/30588393-d0e545c4-9d36-11e7-8dd2-d0d3d51f60a5.PNG)

**Comment by TimGeyssens** [comment]
Hey, what happens if you first save the prop editor with the type selected, does it populate then?

**Comment by TimGeyssens** [comment]
Guessing this is due to the datatype editor that slides in on the doctype... try editing it on the datatype section, should work
