### ISSUE TITLE
Formatting Date using Label Config

### ISSUE THREAD

**Issue by uniquelau** [TimGeyssens/UIOMatic#130]
[UIOMaticListViewField(Name = "Invoice Date", Config = "{'format' : '{{value|relativeDate}}'}")]

Is there a way to find the available filters? I am trying to get my date to display using `shortDate` ? 

Many thanks! Laurie

**Comment by TimGeyssens** [comment]
A bit late but yeah you need to add your own I think, details here http://www.nibble.be/?p=525
