### ISSUE TITLE
Assembly scanning not careful enough

### ISSUE THREAD

**Issue by kipusoep** [TimGeyssens/UIOMatic#134]
Scanning all types in all assemblies can provoke a ReflectionTypeLoadException when something is wrong with an assembly.
In my case I ran into [the famous DotNetOpenAuth issue](https://stackoverflow.com/questions/34236329/mvc-4-mef-system-typeloadexception-inheritance-security-rules-violated-by-type).
I added a try catch to prevent these issues to arise and I'll submit a PR in a few.

**Comment by TimGeyssens** [comment]
Ace, thank you!
