### ISSUE TITLE
Umbraco8 Plan?

### ISSUE THREAD

**Issue by Killerkiwi2005** [TimGeyssens/UIOMatic#143]
Is there any plan for umbraco8

I've had a quick look at the main issue seems to be the installer and tree controller

**Comment by chrno1209** [comment]
I am having the same question too, wonder if it can be available for Umbraco 8 too :)

**Comment by TimGeyssens** [comment]
Yeah I made a quick port a while back but need to test it against the final v8, If anyone is up for helping...

**Comment by Sibren** [comment]
Sure.
Happy to!

Op vr 27 sep. 2019 10:51 schreef Tim Geyssens <notifications@github.com>:

**Comment by Niels84** [comment]
> Yeah I made a quick port a while back but need to test it against the final v8, If anyone is up for helping...

I'm up for helping! Can you publish the port version?

**Comment by TimGeyssens** [comment]
@Sibren @Niels84 sweet thanks, yeah I'll dig it up and publish is shortly (within a week). As for as I can remember the inners worked but the UI needed some refreshing

**Comment by TimGeyssens** [comment]
code is in the v3 branch, tryng to fix the appveyor setup (so there is a nuget) but hitting a small error there for the moment (Umbraco.SqlServerCE.targets(2,1): error MSB4041)

**Comment by Sibren** [comment]
Hi Tim, @Niels84 and I have started to investigate.
We solved a whole lot of (small) issues already, but there are still lots remaining.
What we've got working so far: starting up, creating nodes (although there's a refresh issue), deleting nodes, saving simple nodes (text and password), some styling issues, loading content/media/members (but saving is an issue).

It seems silly to do a pullrequest yet, because of so many things not working, but we'll try to do so on Monday.

**Comment by TimGeyssens** [comment]
Sweet, yeah pull away then we can work on it together 💪

**Comment by Sibren** [comment]
Hi Tim,

I have never created a pullrequest before, but I've created a fork to stash my/our data.
Trying to get the RTE and the datepicker working now.

Main issue now seems to be that there's something weird with creating. Will create screendump later.

**Comment by TimGeyssens** [comment]
@Sibren hey it's pretty easy to do a pull request, but maybe I can just add you as a collab on the project then we can work in the same repo.... is that ok?

**Comment by Sibren** [comment]
Sure, I've accepted your invite.

**Comment by Killerkiwi2005** [comment]
Is there a way to build the v3 branch yet  ? 

"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" build/package.proj

\UIOMatic\src\packages\Umbraco.SqlServerCE.4.0.0.1\build\Umbraco.SqlServerCE.targets(2,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. [\uiomatic\UIOMatic\src\UIOMatic\UIOMatic.csproj]

**Comment by Killerkiwi2005** [comment]
Getting a build error for v3

  82 files to add to Manifest
\uiomatic\UIOMatic\build\package.proj(125,3): error : Name cannot begin with the '8' character, hexadecimal value 0x38. Line 20, position 47.

**Comment by Sibren** [comment]
Please open it in VS 2019

Op di 15 okt. 2019 02:53 schreef KillerKiwi <notifications@github.com>:

**Comment by TimGeyssens** [comment]
Hey mine buikds in vs 2017, what are you using to build @Killerkiwi2005 (I get the same errors on appveyor so would be good to know how to fix)

**Comment by Sibren** [comment]
Still having some issues, but first commit is there:
Fixed RTE, textarea, input (text+pw).
Creating and deleting is now possible, but there's a glitch upon creating with the datepicker (it shows top left) -- it still is the old datepicker, not the Umbraco 8 one.
And if you selected an item and then try to create, it does not refresh the view.

**Comment by TimGeyssens** [comment]
ok super :)

**Comment by TimGeyssens** [comment]
The date(time) picker isn't using a built in Umbraco one but using bootstrap-datetimepicker.js, so we can probably fix that.... what do you mean with select item and create, refresh view?

**Comment by Sibren** [comment]
Hi Tim,

I put it here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/99424-custom-section-issue-with-selecting-the-right-itemscreating-new-ones
(unfortunately in the wrong category).
Yeah, the datepicker could be something I screwed up. Looking into it right now.

**Comment by TimGeyssens** [comment]
Cool, wel propably can be fixed with updating the third party component (datepicker). Just trying to fix appveyor, after that I can look into remaining stuff

**Comment by TimGeyssens** [comment]
@Sibren appears the tree issue is fixed in the Umbraco core (works fine in 8.2), appveyor is also working now...

**Comment by TimGeyssens** [comment]
Gonna close this item now, for v3 issues just report them separately on the issue tracker.
