### ISSUE TITLE
Umbraco V8 Section Missing

### ISSUE THREAD

**Issue by AaronSadlerUK** [TimGeyssens/UIOMatic#152]
Hi,

Not sure if I'm doing something wrong, however I have a fresh install of Umbraco with the latest version of UIOMatic installed.

However I am unable to assign the permission as it does not show in the sections list within the groups, or on the menu.

I've checked the app_plugins folder and it all seems to be there.

Any help is appreciated

**Comment by TimGeyssens** [comment]
Odd, are you an admin on the site?

**Comment by AaronSadlerUK** [comment]
Yes, the only admin on the site

**Comment by TimGeyssens** [comment]
Odd, have you checked the admin user group, to see if it is available there? 

Since it should be checked if this code executes https://github.com/TimGeyssens/UIOMatic/blob/v3/src/UIOMatic/Migrations/3.0.0/AddAllowedSectionToAdmins.cs

**Comment by AaronSadlerUK** [comment]
So this is a completely new install, the only plugin being UIOMatic.

As you can see this is installed via NuGet, nothing shows under the sections options for users to enable it, nor does it show anywhere in the backoffice

![image](https://user-images.githubusercontent.com/9937803/85004556-9a734600-b14f-11ea-8e7a-491c5df2830e.png)

![image](https://user-images.githubusercontent.com/9937803/85004618-ae1eac80-b14f-11ea-8172-b8f1a9f9860d.png)

**Comment by TimGeyssens** [comment]
Odd , section code seems to be ok, I'll check

**Comment by TimGeyssens** [comment]
Just did a fresh install and works like it should... 
![image](https://user-images.githubusercontent.com/2988648/85012586-85081700-b163-11ea-982c-d9dddd241a48.png)

Are you sure the ui o matic references are there? 
![image](https://user-images.githubusercontent.com/2988648/85012688-acf77a80-b163-11ea-91c1-b6b8a956a715.png)

Maybe the nuget install didn't go ok?

**Comment by AaronSadlerUK** [comment]
Strange, yes the reference is there.

I will try another clean install and report back shortly

**Comment by TimGeyssens** [comment]
which v of umbraco are you running? I'm on latest 8.6.X

**Comment by AaronSadlerUK** [comment]
The current version is on 8.6.1

**Comment by TimGeyssens** [comment]
Ok odd, let me know if it any different on a fresh install

**Comment by AaronSadlerUK** [comment]
Ok so I finally managed to do a clean install.

Umbraco 8.6.2 with UIOMatic v3.0.9

Same as above.

The dependency setting for both is "Highest", I wonder if this could be the problem?

**Comment by AaronSadlerUK** [comment]
I have pushed the install for your reference:

https://github.com/AaronSadlerUK/UIOMatic

**Comment by TimGeyssens** [comment]
Thanks, I'll take a look tomorrow, might be... is the other project also colled UIOMatic? Maybe that conflicts some how...

**Comment by AaronSadlerUK** [comment]
I never thought of that 😂

I'll try tomorrow with a differently named project

**Comment by TimGeyssens** [comment]
ok , let me know how that goes

**Comment by AaronSadlerUK** [comment]
Ok, so it seems that was the problem.

**Comment by TimGeyssens** [comment]
Awesome, thanks for testing!
