### ISSUE TITLE
Support Content Apps

### ISSUE THREAD

**Issue by skartknet** [TimGeyssens/UIOMatic#161]
It would be great if the types supported Content Apps.

**Comment by skartknet** [comment]
I have created a PR #162 But I need some help with it, it's not fully working.

**Comment by TimGeyssens** [comment]
Pull request is completed now... just needs some docs / info :)

**Comment by skartknet** [comment]
awesome. Yes, I forgot the docs 😋 , I'll put something together.

**Comment by TimGeyssens** [comment]
fixed by @skartknet with pr #162 :) coming up in the hacktober release!
