### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by toliphant** [TimGeyssens/UIOMatic#165]
In your list.ontroller.js you added this little bit in there in the past couple months:

if (!firstLoad) {
loadState();
 } else {
saveState();
}

However, it seems to be messing with the pagination in list view. I removed the ! on firstLoad and it seems to work fine now.

**Comment by TimGeyssens** [comment]
ok thanks for reporting, will check it out!

**Comment by benjaminc** [comment]
I found the same thing.  I'll submit a PR to fix this in just a minute

**Comment by TimGeyssens** [comment]
@benjaminc sweet, thanks!

**Comment by TimGeyssens** [comment]
fixes with pr #167
