### ISSUE TITLE
Docs for making custom sections

### ISSUE THREAD

**Issue by skttl** [TimGeyssens/UIOMatic#169]
It seems like it's possible to do custom sections, in stead of the default UI-O-Matic one (#77). But how is it done?

Would love to see this in the docs :)

**Comment by TimGeyssens** [comment]
good call, yes I would also like to know :p

**Comment by skttl** [comment]
@ProWorksDevTeam @benjaminc can you help?

**Comment by benjaminc** [comment]
@skttl @TimGeyssens I believe PR #170 should cover it, but let me know if I missed anything.

**Comment by TimGeyssens** [comment]
Looks good thanks! Boom! Pr 3 for hacktoberfest

**Comment by TimGeyssens** [comment]
Also part of the gitbook docs now :) https://timgeyssens.gitbook.io/ui-o-matic/

**Comment by benjaminc** [comment]
I don't see it at https://timgeyssens.gitbook.io/ui-o-matic/12.advanced.  Does it take a bit to update, or did I do something wrong in how I coded it?

**Comment by TimGeyssens** [comment]
No no, I moved it to a separate page :) https://timgeyssens.gitbook.io/ui-o-matic/custom-sections thanks again @benjaminc !
