### ISSUE TITLE
ItemName not working in backoffice

### ISSUE THREAD

**Issue by AaronSadlerUK** [TimGeyssens/UIOMatic#175]
I have set the itemName within the poco class, however in the backoffice it is showing the class name instead.

This is with Umbraco 8.10.0

![image](https://user-images.githubusercontent.com/9937803/103366720-444a6c80-4abb-11eb-8a69-9bc104eae6d9.png)
![image](https://user-images.githubusercontent.com/9937803/103366735-4d3b3e00-4abb-11eb-8902-e87cd6b81f30.png)

**Comment by TimGeyssens** [comment]
is that in the tree? item name isn't ued in the tree, for the tree you need to implement the tostring method

**Comment by TimGeyssens** [comment]
As noted here https://timgeyssens.gitbook.io/ui-o-matic/untitled#override-the-tostring-method

**Comment by AaronSadlerUK** [comment]
Thanks @TimGeyssens!
