### ISSUE TITLE
Format in listview

### ISSUE THREAD

**Issue by paulsoerensen** [TimGeyssens/UIOMatic#19]
Would be nice to decorate the field attribute with a ex Format="dd-MM-yyyy" to format the columns in the listview. This could of course also be used for numbers etc.

**Comment by serenabenny** [comment]
@paulsoerensen Fixed on https://github.com/serenabenny/UIOMatic branch.

**Comment by TimGeyssens** [comment]
@serenabenny any chance you can provide a pull request for that feature, would be ace  :)

**Comment by serenabenny** [comment]
@TimGeyssens Too many new feature now including the branch. Like data filtering ,default filter ,  default sorting, Export to CSV file. It's difficult to split them. sorry about that. :(

**Comment by TimGeyssens** [comment]
@serenabenny no worries, awesome work, will see if I can cherry pick some of the items

**Comment by TimGeyssens** [comment]
@serenabenny could you maybe point me in the direction of the field format stuff (where it's located in the code)?

**Comment by serenabenny** [comment]
UIOMaticFieldAttribute
public string DataFormat { get; set; } 
UIOMaticPropertyInfo.cs
+
 +        public string DataFormat { get; set; } 
PetaPocoObjectController.cs
+                            DataFormat = attri.DataFormat
                          };		                          };
                          yield return pi;		                          yield return pi;
                      }		                      }
 @@ -271,8 +272,8 @@ public IEnumerable<UIOMaticPropertyInfo> GetAllProperties(string typeName, bool
                              Tab = "Misc",		                              Tab = "Misc",
                              Description = string.Empty,		                              Description = string.Empty,
                              View = IOHelper.ResolveUrl(view),		                              View = IOHelper.ResolveUrl(view),
 -                            Type = prop.PropertyType.ToString()		 +                            Type = prop.PropertyType.ToString(),
 -		 +                            DataFormat = ""
                          };		                          };
                          yield return pi;		                          yield return pi;
                      }		                      }


list.controller.js
if ($scope.rows.length > 0) {
                    $scope.csvheader = Object.keys($scope.rows[0]).filter(function (c) {
                        return $scope.ignoreColumnsFromListView.indexOf(c) == -1;
                    });
                    $scope.cols = $scope.properties.filter(function (c) {
                        return $scope.ignoreColumnsFromListView.indexOf(c.Key) == -1;
                    });
                }



uioMaticObjectResource.getAllProperties($scope.typeName, true).then(function (response) {
                $scope.properties = response.data;
            });

List.html
<tr>
                                <td style="width:35px" ng-hide="IsReadOnly"></td>
                                <td ng-repeat="col in cols">
                                    <a href="" class="sortable" ng-click="order(col)">{{col.Name}}</a>
                                    <i class="icon" ng-class="{'icon-navigation-up': reverse, 'icon-navigation-down': !reverse}" ng-show="IsOrder(col)"></i>
                                </td>
                            </tr>
                            </thead>
                            <tbody>
                            <tr ng-repeat="row in rows" ng-class="{selected: isRowSelected(row)}">
                                <td style="width: 35px" ng-hide="IsReadOnly">
                                    <i class="icon icon-edit"></i>
                                    <input type="checkbox" name="selectedItems[]" value="{{getObjectKey(row)}}" ng-checked="isRowSelected(row)" ng-click="toggleSelection(getObjectKey(row))"/>
                                </td>
                                <td ng-repeat="column in cols ">
                                    <div ng-switch ="isColumnLinkable(column,$index)">
                                        <a href="#/{{currentSection}}/uioMaticTree/edit/{{getObjectKey(row)}}%3Ftype={{typeName}}" ng-switch-when="true">{{row[column.Key]}}</a>
                                        <Div ng-switch-when="false">
                                            <div ng-switch on="isDateTime(column)">
                                                <span ng-switch-when="true">{{row[column.Key]?(millisToUTCDate(row[column.Key]) | date:column.DateFormat?column.DateFormat:'yyyy-MM-dd HH:mm:ss'):" "}}</span>
                                                <span ng-switch-default>
                                                    {{row[column.Key]}}
                                                </span>
                                            </div>
                                            
                                            </Div>
                                    </div>
                                </td>
                            </tr>

**Comment by serenabenny** [comment]
@TimGeyssens you can check the latest commit.I 'm not sure maybe  have some relate function.

**Comment by serenabenny** [comment]
@TimGeyssens Maybe also pick up the about the list header section. I fixed that issue.

**Comment by TimGeyssens** [comment]
@serenabenny ok thanks that helps :)

**Comment by moytho** [comment]
I'm trying to decorate my DateTime fields atribute with Format="dd-MM-yyyy" to format the columns in my listview, is this feature released already? do you have a short snippet of how I can use it in my class?

**Comment by TimGeyssens** [comment]
Nope haven't merged that in, but you can use the branch from @serenabenny https://github.com/serenabenny/UIOMatic

**Comment by TimGeyssens** [comment]
Plan is to have this in version 2, you'll be able to setup a list view view, so that goes even further then a simple format, kudos to Matt since he is making this possible https://github.com/mattbrailsford/UIOMatic

**Comment by TimGeyssens** [comment]
Part of Matts pull request https://github.com/TimGeyssens/UIOMatic/pull/48 (you can then also have a view for the list view fields)
