### ISSUE TITLE
Update umbraco 9

### ISSUE THREAD

**Issue by marciogoularte** [TimGeyssens/UIOMatic#193]
Hi,I did an upgrade to umbraco 9. It's working very well. But I couldn't make a pull request. How can I proceed?

![matic](https://user-images.githubusercontent.com/215987/134827439-03ba17d5-75c9-4519-9869-1c28c80a4ae9.gif)

**Comment by TimGeyssens** [comment]
wow sweet @marciogoularte ! well did you make a fork on github? Then you should just be able to create a pull request? https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by TimGeyssens** [comment]
alternatively you can also send me the files and I can setup a new branch

**Comment by TimGeyssens** [comment]
@marciogoularte ? Let me know how I can help :)

**Comment by marciogoularte** [comment]
Hi, i made a pull request. As you may know, Umbraco v9 everything is by DI. We no longer have `Umbraco.Core.Composing.Current`.  UIOMatic uses static classes using Umbraco v8 `Current`, I had to make a service locator. But I believe that temporary, we can improve this

**Comment by TimGeyssens** [comment]
Sweeeeet! Thank you so much. Just need to see how I can merge to a new branch. @marciogoularte

**Comment by TimGeyssens** [comment]
merged to a new branch @marciogoularte , now just need to figure out why the automated build doesn't work

**Comment by sbosell** [comment]
Looking forward to seeing this released!

**Comment by TimGeyssens** [comment]
@marciogoularte mananaged to get the appveyor build working https://www.nuget.org/packages/Nibble.Umbraco.UIOMatic/

**Comment by TimGeyssens** [comment]
not sure if the nuget package needs to change...

**Comment by marciogoularte** [comment]
Hi @TimGeyssens . I'm not sure either

**Comment by TimGeyssens** [comment]
yeah need to look into it, doesn't seem to do the correct stuff...

**Comment by harvzor** [comment]
I'm trying it out now. I had the issue:

```
System.InvalidOperationException: Unable to resolve service for type 'UIOMatic.IUIOMaticHelper' while attempting to activate 'UIOMatic.Web.Controllers.UIOMaticTreeController'.
```

Adding:

```
services.AddSingleton<IUIOMaticHelper, UIOMaticHelper>();
```

In my `Startup.ConfigureServices` method seemed to help.

## Update

I'm trying to upgrade to Umbraco v9 but the site was having a strange issue:

```
No controller/action found by name Render.Index
```

My project structure is like:

- Web
  - Depends on Nibble.Umbraco.UIOMatic
- Core
  - Depends on Nibble.Umbraco.UIOMatic.Core

Seems that `Nibble.Umbraco.UIOMatic.Core` depends on `Umbraco.Cms.Core ≥ 9.0.0` and `Umbraco.Cms ≥ 9.0.0`, but I doubt it should be using `Umbraco.Cms`?

I don't want my `Core` project to have a sub-dependency of `Umbraco.Cms` as it adds files like `~/umbraco/UmbracoWebsite/NoNodes.cshtml` which I think messes with the build.

My site doesn't really need UIOMatic that much so I'm disabling it now. Not looking for a solution anytime soon, thought I'd just add my thoughts.

**Comment by TimGeyssens** [comment]
thanks @Harvzor , yeah the nuget package needs some work, thanks for letting me know

**Comment by davidsandstrom** [comment]
What do i have to do to get this working?
Registered .AddUIOMatic() in startup but now i get a null reference exception in /umbraco/ServerVariables:
"NullReferenceException: Object reference not set to an instance of an object.
UIOMatic.Web.UIOMaticServerVariablesHandler.Handle(ServerVariablesParsingNotification notification)" in backoffice and a bunch of errors from angular.

**Comment by TimGeyssens** [comment]
@marciogoularte any pointers?

**Comment by dataworking** [comment]
> What do i have to do to get this working? Registered .AddUIOMatic() in startup but now i get a null reference exception in /umbraco/ServerVariables: "NullReferenceException: Object reference not set to an instance of an object. UIOMatic.Web.UIOMaticServerVariablesHandler.Handle(ServerVariablesParsingNotification notification)" in backoffice and a bunch of errors from angular.

That will be missing config elements in appsettings.json - I commented in more detail in https://github.com/TimGeyssens/UIOMatic/issues/197

**Comment by TimGeyssens** [comment]
version 4.1.0 adds default config
