### ISSUE TITLE
Save data to model.value instead of property.value so that we can use existing property editors

### ISSUE THREAD

**Issue by mmadukah** [TimGeyssens/UIOMatic#196]
My team is upgrading an application from Umbraco 7 to 8. We currently use Fluidity to perform CRUD operations on our custom tables. Unfortunately, this doesn't appear to work with Umbraco 8. 

We have decided to migrate from Fluidity to UIOMatic but we are noticing that it doesn't seem to have the simple support for Umbraco property editors and our custom controls. I believe that the reason for this is that it saves data to `property. value` rather than `model.value`.

I understand that new custom property editors can be created that saves to `property.value` but this seems like unnecessary work. 

It would be great if UIOMatic allowed the use of these existing property editors without all the additional work.

**Comment by TimGeyssens** [comment]
sure would be up for a pullrequest

**Comment by TimGeyssens** [comment]
possible in v10
