### ISSUE TITLE
links to nibble.be not working on https://github.com/TimGeyssens/UIOMatic/blob/v3/docs/14.FurtherReading.md 

### ISSUE THREAD

**Issue by teusch** [TimGeyssens/UIOMatic#199]
The links to nibble.be on https://github.com/TimGeyssens/UIOMatic/blob/v3/docs/14.FurtherReading.md don't seem to be working:

- [UI-O-Matic V2 and custom repositories](http://www.nibble.be/?p=537)
- [Extending UI-O-Matic V2 With custom List View filters](http://www.nibble.be/?p=525)
- [Extending UI-O-Matic v2 with custom List Actions ](http://www.nibble.be/?p=520)  
- [Using UI-O-Matic V2 as an entries viewer for your custom forms](http://www.nibble.be/?p=515)

**Comment by TimGeyssens** [comment]
yeah site is down but should still be available on https://archive.org/web/

**Comment by patrickdemooij9** [comment]
@TimGeyssens would it be an idea to move those articles to the documentation?

**Comment by TimGeyssens** [comment]
@patrickdemooij9 yes! good idea

**Comment by TimGeyssens** [comment]
for the time being I just updated the links to archived pages
