### ISSUE TITLE
Media Picker on People throws 401

### ISSUE THREAD

**Issue by Mantus667** [TimGeyssens/UIOMatic#2]
When clicking on the picker to select an image for a poeple object the media picker throws a 401 exception and redirect to login page.

User is still logged in to backoffice.

**Comment by TimGeyssens** [comment]
Hmm when exactly does this happens (on everyclick of the file picker) seems fine here

**Comment by TimGeyssens** [comment]
Still can't reproduce, does it still happen when you pull the latest version?

**Comment by Mantus667** [comment]
Will try with the latest version and see if it's still there.
Was on every click on the button to open the file picker

**Comment by TimGeyssens** [comment]
Okido :)

**Comment by TimGeyssens** [comment]
Any luck so far with latest version?

**Comment by Mantus667** [comment]
Don't mind my stupid talking.
Had a look and the user wasn't allowed to see the media section. So the error was right.

**Comment by TimGeyssens** [comment]
Ok makes sense now :) thanks for testing!
