### ISSUE TITLE
Issue with Umbraco 10

### ISSUE THREAD

**Issue by huzzi** [TimGeyssens/UIOMatic#219]
Does not seems to work with Umbraco 10, it adds the nuget package to the project file but does not copy the html/js/css files.

**Comment by patrickdemooij9** [comment]
Hi @huzzi 
The html/js/css files should be done through the razor class library, so you won't see them in your project, but they will be there when deploying. If you build and run the application, does it give you an error when trying to resolve the files?

**Comment by huzzi** [comment]
> Hi @huzzi The html/js/css files should be done through the razor class library, so you won't see them in your project, but they will be there when deploying. If you build and run the application, does it give you an error when trying to resolve the files?

Hi @patrickdemooij9 when I build and run I get a blank page, no errors. I will try on a clean install. Thanks

**Comment by huzzi** [comment]
@patrickdemooij9 it seems to have worked on a clean install but I'm having issue on upgrade from V8 to V10. I'm maybe doing something wrong there.

**Comment by huzzi** [comment]
Okay, I have the model files in a a separate project which does not work, moving the files to the web projects seems to work. Not sure why that is but it was working fine on V8.

Also, can someone share sample code for event handler? I want to do something with the data before it's saved.
