### ISSUE TITLE
Format column header to match UIOMaticField name

### ISSUE THREAD

**Issue by reights** [TimGeyssens/UIOMatic#22]
the columns are showing the property name and not the UIOMaticField name

**Comment by TimGeyssens** [comment]
Yup currently they do, would be nice to show the name instead

**Comment by serenabenny** [comment]
@reights Find the soulation at https://github.com/serenabenny/UIOMatic2

**Comment by TimGeyssens** [comment]
@serenabenny mind pointing me to the files that I need in order to get this feature in UI-O-Matic?

**Comment by serenabenny** [comment]
@TimGeyssens 

For list.controller.js
![image](https://cloud.githubusercontent.com/assets/3369365/16911453/24413984-4d11-11e6-80a3-022515e97267.png)

![image](https://cloud.githubusercontent.com/assets/3369365/16911489/58d0f3ce-4d11-11e6-8ff6-b4d51305ed42.png)

For list.html
![image](https://cloud.githubusercontent.com/assets/3369365/16911522/89b3e014-4d11-11e6-99b6-274078848366.png)

**Comment by TimGeyssens** [comment]
@serenabenny awesome thanks for the details!

**Comment by TimGeyssens** [comment]
Part of Matts pull request https://github.com/TimGeyssens/UIOMatic/pull/48
