### ISSUE TITLE
Event handing with Umbraco 10

### ISSUE THREAD

**Issue by huzzi** [TimGeyssens/UIOMatic#222]
Can someone please help me with event handling with Umbraco 10? I need to add some logic before saving / update and deleting a record.

Many thanks

**Comment by Jogai** [comment]
I dont think this is the place to ask, but here you go: https://docs.umbraco.com/umbraco-cms/reference/notifications/contentservice-notifications

**Comment by huzzi** [comment]
@Jogai I mean event handling for UIOMatic (UIOMatic.ObjectEventArgs) not for Umbraco events

**Comment by huzzi** [comment]
Old event handling code for Umbraco 8 still works.
