### ISSUE TITLE
Missing methods on pickers.object.controller.js

### ISSUE THREAD

**Issue by huzzi** [TimGeyssens/UIOMatic#225]
The object picker does not work without these two methods.

              `submit: function (selectedIds) {
                    $scope.selectedIds = selectedIds;
                    getFullDetails();
                    editorService.close();
                },
                close: function () {
                    editorService.close();
                }`

I've updated the file with the missing methods, please kindly review and merge. Thank you

https://github.com/TimGeyssens/UIOMatic/pull/224

**Comment by huzzi** [comment]
Could someone please review and merge this PR? Thank you.

**Comment by TimGeyssens** [comment]
merged and should be available in  5.1.5
