### ISSUE TITLE
System.Runtime.Serialization.DataMember overrides Uiomatic Ignore attributes

### ISSUE THREAD

**Issue by madsoulswe** [TimGeyssens/UIOMatic#24]
Properties with **[DataMember]** gets included in list even if **[UIOMaticIgnoreFromListView]** is set.

**Comment by madsoulswe** [comment]
FYI: I love uiomatic!

**Comment by TimGeyssens** [comment]
Hmm that's strange, I'll have a look! Thanks for reporting!

**Comment by TimGeyssens** [comment]
Hmm can't reproduce atm, mind sending me an example class?

**Comment by TimGeyssens** [comment]
@madsoulswe still having this issue? Mind sending me an example model?

**Comment by TimGeyssens** [comment]
Closed for now since I can't reproduce
