### ISSUE TITLE
File picker not working with new install Umbraco 7.4.2

### ISSUE THREAD

**Issue by ThumNet** [TimGeyssens/UIOMatic#25]
Hi Tim,

I found an issue with the file (media) picker, when using a fresh Umbraco 7.4.2 site.

![issue](https://cloud.githubusercontent.com/assets/692308/14457843/c48b9962-00ad-11e6-8b82-8d2a2c550e7f.PNG)

**Steps to reproduce:**

1. Create a new empty Web project
2. Install-Package UmbracoCms
3. Install-Package Nibble.Umbraco.UIOMatic
4. Create the sample People table and Person model
5. Go to the backoffice and try selecting an image for a person

**Research:**
I've also forked your solution and upgraded the UmbracoCms package to 7.4.2 and then the issue doesn't occur. After some digging I found that in the Umbraco site another editor is configured, which returns a different value (an object instead of a string).

Fresh install:
![editor-imagecropper](https://cloud.githubusercontent.com/assets/692308/14457896/24721e8c-00ae-11e6-86c5-46a92f84b199.PNG)

Your project upgraded:
![editor-uploadfield](https://cloud.githubusercontent.com/assets/692308/14457905/322efe0a-00ae-11e6-9cce-aa415e49a225.PNG)

**Suggested fix:**
One solution would be using the image property of the item (which works both cases), but I don't know for sure if this is the best approach
![other-property](https://cloud.githubusercontent.com/assets/692308/14458052/0deee874-00af-11e6-922e-857a8d6a521b.PNG)

[Commit](https://github.com/ThumNet/UIOMatic/commit/356909b962654c073ed03e2cb424c7d57db9863d)

**Comment by TimGeyssens** [comment]
Will have a look, thanks for reporting!

**Comment by TimGeyssens** [comment]
Fixes in latest commit (and version 1.7.2)
