### ISSUE TITLE
Introduce a Core package

### ISSUE THREAD

**Issue by ThumNet** [TimGeyssens/UIOMatic#26]
Hi Tim,

We have a specific solution structure at our company, this requires us to define the Models in a seperate Data/Models project. We'd like to use the UIOMatic inside our Umbraco project but when including the UIOMatic package the entire UmbracoCms package is installed, this is not desired.

What do you think of the introducing an UIOMatic.Core project (which only requires UmbracoCms.Core), I've already created some commits https://github.com/ThumNet/UIOMatic/commit/cc7f0531aaad23321a98329ee504a20cbba2de65 and https://github.com/ThumNet/UIOMatic/commit/286981759ef2c96cc05b724d13e2a763ee24ce5f with the suggested change :)

I'm interested in your thoughts on the matter!

Regards,
Jeffrey

**Comment by TimGeyssens** [comment]
Yeah makes sense! Would be ace if you could provide a pull request for it :)

**Comment by ThumNet** [comment]
Pull request created as requested :)

**Comment by TimGeyssens** [comment]
Sorry haven't merged this in yet, plan is to do so in v2 coming shortly

**Comment by TimGeyssens** [comment]
Part of Matts pull request https://github.com/TimGeyssens/UIOMatic/pull/48
