### ISSUE TITLE
UiOMatic not showing up in the backoffice

### ISSUE THREAD

**Issue by ryanology** [TimGeyssens/UIOMatic#28]
Hi Tim,

I installed the nuget package but unfortunately it is not showing up in the backoffice.  Not getting any console errors or tracelog errors.  We are using UaaS, but this current issue happens on my local version (cloned from UaaS).  The current Umbraco version is 7.4.3.  Also want to note that I have the Umbraco website in one project, and all of the models/controllers/etc. in another project (using strongly typed views).  That other project only had the Umbraco core binaries, but the nuget dependencies downloaded Umbraco CMS 7.4.1 (which I then upgraded to 7.4.3).

Any ideas what might be happening here, or what else I can try?

Best,
Ryan

**Comment by ThumNet** [comment]
Hi Ryan,

I had the same issue, have you given the backoffice user access to the new UI-O-Matic section?

Regards,
Jeffrey

**Comment by ryanology** [comment]
Thanks a bunch Jeffrey, that did the trick. I'm an admin so that didn't cross my mind (yet it's so simple).
