### ISSUE TITLE
Foreign Keys in list view with dropdown

### ISSUE THREAD

**Issue by pseudyx** [TimGeyssens/UIOMatic#29]
Hi, I have followed the solution "Foreign Keys with Label view" on umbraco.org: 
https://our.umbraco.org/projects/developer-tools/ui-o-matic/computer-says-no/73973-foreign-keys-with-label-view

to enable foriegn key values. But I'm not having any luck... the only difference is, the fields are dropdown fields.

I have added a comment to the above link... but essentially all I'm trying to do is show the value in listview of a foreign key

**Comment by TimGeyssens** [comment]
Not an issue, will respond on the forum
