### ISSUE TITLE
Entity Framework?

### ISSUE THREAD

**Issue by nojaf** [TimGeyssens/UIOMatic#3]
Any plans on making this work with Entity Framework instead of PetaPoco?

**Comment by TimGeyssens** [comment]
Well I plan on making it a provider model so that you can switch out the controller and could create an Entity Framework one. But must say I haven't looken into entity framework that much so not sure how different it would be from the Petapoco default provider

**Comment by TimGeyssens** [comment]
But that way you could also point it to othet data sources

**Comment by TimGeyssens** [comment]
So you would have to implement this interface https://github.com/TimGeyssens/UIOMatic/blob/master/src/UIOMatic/Interfaces/IUIOMaticObjectController.cs

**Comment by nojaf** [comment]
Thanks Tim, exactly what I'm looking for.
Where would the entry point be to set the IUIOMaticObjectController?
And what is the typeName param? CLR typename?

**Comment by TimGeyssens** [comment]
Still need to make the entry point, will probably be a config file where you can set the default provider, yeah typename is CLR typename so you can do Type.GetType(typeName)

**Comment by TimGeyssens** [comment]
Latest commit introduces config file that allows you to specify the default object controller https://github.com/TimGeyssens/UIOMatic/commit/f2df3fa4b37585ffbf1955e0058f362b0d5a2dcb so you can now swap PetaPoco out with entity framework or you could also use different data sources

**Comment by stefankip** [comment]
So I'm in the same situation right now and don't really know where to start. Does anyone have an EF implementation example I can borrow?

**Comment by stefankip** [comment]
I think I worked it out with the `AbstractUIOMaticRepository`, which is a bit easier to implement ;-)

**Comment by TimGeyssens** [comment]
Sweet :)
