### ISSUE TITLE
DateTime picker with time

### ISSUE THREAD

**Issue by asempf** [TimGeyssens/UIOMatic#37]
the date time picker with time, when displaying existing value is displaying incorrect time.

EG
Database record: "2016-08-17 06:00:00.000"
displaying in editor as "2016-08-17 16:00:00"

![image](https://cloud.githubusercontent.com/assets/21031042/17757550/e7db30ee-652a-11e6-841a-66702899dcec.png)

**Comment by asempf** [comment]
we are in +10 timezone (Australia)... so I assume it is adding the +10 offset... but how can we stop the offset from being added to datetimes that already exist when being displayed through the picker?

**Comment by TimGeyssens** [comment]
Thanks for reporting, will try to take a look soon (of if you feel up to the challenge feel free to make a pull request :) )

**Comment by TimGeyssens** [comment]
Think I fixed it, rolling out a new version today

**Comment by pseudyx** [comment]
Awesome...  I will update and test. Thank you

**Comment by TimGeyssens** [comment]
New build is running now so you should be able to upgrade to version 1.8.1 shortly (make sure to clear browser cache since it's a js file change)
