### ISSUE TITLE
Make it possible to hide a UI-O-Matic model from the tree

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#42]
In case you just want to use it as prop editor and not have it in the backoffice

**Comment by mattbrailsford** [comment]
Is this so you can just have database values in a dropdown as a property editor without having an actual UI-O-Matic UI for it? Wondering if in that case, something like nuPickers wouldn't be a better solution? Just feels a bit "against the grain" that you would tell a model to be UIOMatic, but then tell it not to be editable via UIOMatic if you see what I mean?

**Comment by mattbrailsford** [comment]
The only other reason I could see (which may actually be valid) is if you don't want it to appear in the tree, but want it listable / editable via a "list" field view to mimic a kind of "Nested Listview". Would this be a valid use case? and have you tested this would work? If so, then I could see the value in it for this.

**Comment by TimGeyssens** [comment]
Well it was due to a feature request I got, the folks had a lot of foreign key tables with only key/value that didn't need to be editable in the backoffice, but yeah the scenario that you provide would also be valid
