### ISSUE TITLE
How do you get an Icon in the Applications panel in Umbraco CMS?

### ISSUE THREAD

**Issue by jonathanS8080** [TimGeyssens/UIOMatic#47]
How do you get an Icon in the Applications panel in Umbraco CMS?

**Comment by TimGeyssens** [comment]
Completely custom one or one from the Helveticons icons pack used in Umbraco?

**Comment by jonathanS8080** [comment]
I had i working in Umbraco 7.4.3 and now I have upgraded to 7.5.4 the icon is missing and i cant for the life of me work out why it has disappeared.

**Comment by TimGeyssens** [comment]
Well it fetches it from the applications.config, you can either set it to a custom file or use one of the Helveticons

**Comment by jonathanS8080** [comment]
If I navigate to /uiomatic in the CMS it redirects me back to the content page.

**Comment by TimGeyssens** [comment]
Did you clear your browser cache after the upgrade?

**Comment by jonathanS8080** [comment]
I did a clientDependency tweak and webconfig tweak - do i need to do anything else?

**Comment by jonathanS8080** [comment]
Yep - I have just tried that too.

**Comment by jonathanS8080** [comment]
Is it possible to re-install it through the Packages panel in the CMS?

**Comment by TimGeyssens** [comment]
Nope since it isn't a Umbraco package, it's only available trough nuget

**Comment by TimGeyssens** [comment]
So in package manager console you could type Update-Package -reinstall Nibble.Umbraco.UIOMatic

**Comment by jonathanS8080** [comment]
I'll give that a go :)

**Comment by jonathanS8080** [comment]
Im really sorry for wasting your time - The tick box in the User Profile page was unticked for UIOMatic. Ticking it made it visible again.
Thanks for all your help,
Jon

**Comment by TimGeyssens** [comment]
No worries glad it is sorted :)

**Comment by jonathanS8080** [comment]
Could I quickly ask? What populates the Name [sections_uiomatic] with the correct Title in the /uiomatic page?

**Comment by TimGeyssens** [comment]
Sure well it comes from the config/lang/en.xml file, in the sections element.
