### ISSUE TITLE
V2 Multi Picker Prop Editor doesn't seem to work anymore

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#53]
Not getting any results back and when you search you get an error

INNER EXCEPTION

System.Data.SqlServerCe.SqlCeException: The column name is not valid. [ Node name (if any) = ,Column name = a ]

**Comment by mattbrailsford** [comment]
I think this and the search dialog is one of the elements I've neglected to keep up to date so yea, probably needs looking at.

**Comment by TimGeyssens** [comment]
Yup I'll take a look :)
