### ISSUE TITLE
Introduce a provider model for list actions

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#55]
Just an idea, but a way to have other actions then just delete available in the list view (and folks can plug and play custom ones by just working with a provider model)

**Comment by mattbrailsford** [comment]
I was pondering something similar as in a previous project using something similar to UI-O-Matic I added an "import" button so could be cool to allow something like this. Just need to think how it will all work visually (don't want to end up with tons of buttons across the top).

**Comment by TimGeyssens** [comment]
True, and you can have global actions like import/export and then record specific actions (visible once you select 1 or more objects), so would definitely need a clean UI

**Comment by TimGeyssens** [comment]
Jus thinking out loud here, a global action (like export) could just consist of an alias, name, location to view (dialog that would open for each one) and the types you wish to have it available on (if not supplied it will be available on all)...

**Comment by mattbrailsford** [comment]
I haven't thought it through myself yet, but I was thinking something like having an Action base class, and on the UIOMatic attribute maybe have an ActionTypes[] property which lists the actions you want to allow on that type. The Action type then exposes whatever we need.

I guess we should think of the different types of actions, as "Export to CSV" could probably work without needing a dialog, where as an "Import" would more than likely need one, so need to cater for both. Not sure what others there might be?

**Comment by mattbrailsford** [comment]
Just for reference, this is what you would add to a DEWD config to add a custom button

    <button type="TableButton" icon="import.png" text="Import Gallery Items" onClientClick="UmbClientMgr.openModalWindow('/App_Plugins/GalleryItemImporter/GalleryItemImporter.aspx?Event=tdf', 'Import gallery item', true, 600, 400);return false;" />

**Comment by TimGeyssens** [comment]
Ok so in that case it also just opens a third party window.

Export could be in different formats so that could need a dialog

**Comment by TimGeyssens** [comment]
But yeah would indeed be better if you define the actions on the UIOMatic attribute 

You could also have like a report, that shows nice charts and all

**Comment by mattbrailsford** [comment]
True, so if we say they all must expose a dialog? We could make them something like the Folders

    [UIOMaticAction("export", "Export", View = "~/path/to/view.html")]
    public class ExportAction {}

Then on the type you'd do like

    [UIOMatic("alias", "Things", "Thing", Actions = new[]{ typeof(ExportAction) })]
    public class Thing {}

Although that does mean you are making ExportAction for no real reason, but the only other way I can think is to declare them on the type, but that could get bulky too

    [UIOMatic("alias", "Things", "Thing")]
    [UIOMaticAction("export", "Export", View = "~/path/to/view.html")]
    [UIOMaticAction("impot", "Import", View = "~/path/to/view.html")]
    public class Thing {}

Any thoughts?

**Comment by mattbrailsford** [comment]
I guess defining the empty classes though does make it easier to reuse, rather than entering view paths constantly, though you could move those to a constants file.

**Comment by TimGeyssens** [comment]
Yup I like that (with the empty classes), like that you can then define the actions on the UIOMatic attribute, think that is the most readable/ understandable

**Comment by TimGeyssens** [comment]
Added the initial code to make this possible https://github.com/TimGeyssens/UIOMatic/commit/3b3c5b4602b26bf5d7d5ae1efb18fb1ed4a0be21

**Comment by TimGeyssens** [comment]
Implemented and even have docs http://www.nibble.be/?p=520 , will move this our markdown docs

**Comment by mattbrailsford** [comment]
Just looking back at this and am wondering, should the ListActions property on the UIOMatic attribute be named "ListViewActions"? I know it's a bit longer, but then everything else we have is "ListView" like "UIOMaticListViewField" and "UIOMaticListViewFilter" etc. What are your thoughts? I'm just a stickler for consistency :)

**Comment by mattbrailsford** [comment]
Alternative is to look at renaming the other items to just be "List" not "ListView".

Or we can just leave things as is :)

**Comment by TimGeyssens** [comment]
Ah no ListViewActions are fine, will update, good catch :)

**Comment by TimGeyssens** [comment]
Updated in https://github.com/TimGeyssens/UIOMatic/commit/cb20160cf89c77b76816dd0b619dc29bf023358b
