### ISSUE TITLE
Can't submit an empty date/datetime value

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#59]
```
An error occured

Error converting value {null} to type 'System.DateTime'. Path 'Birthday', line 1, position 23.

EXCEPTION DETAILS

Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path 'Birthday', line 1, position 23.
```

**Comment by TimGeyssens** [comment]
FIxes in commit  8c46140725de415b48c6d9d6b7b6f5b297515d07

**Comment by TimGeyssens** [comment]
Must be due to change https://github.com/TimGeyssens/UIOMatic/commit/e345920b2242e29a97f9346ff7d722435b11d619 not sure how best to fix @mattbrailsford , or should a datetime property be marked as nullable if it's not mandatory?

**Comment by mattbrailsford** [comment]
Assign to me and I'll take a look at best option

**Comment by mattbrailsford** [comment]
@TimGeyssens do you have a specific reason for offsetting DateTime values in edit.controller? I'm thinking this might be best off moved to the date field editors as then we can check the true value passed down which would be 0001-01-01T00:00:00, where as currently, the offsetting code is giving it a local offset so harder to compare later on.

**Comment by TimGeyssens** [comment]
Ah yes good idea, that should be the way forward

**Comment by mattbrailsford** [comment]
@TimGeyssens can  you explain what the DateTimeOffset field editor is for?

**Comment by TimGeyssens** [comment]
was added by @camaya , care to share some more info @camaya ?

**Comment by camaya** [comment]
The DateTimeOffset field is what you should use when you use the DateTimeOffset type on SQL Server. It should be handled different than a normal DateTime. You can find the technical details on the commits https://github.com/TimGeyssens/UIOMatic/pull/40/commits

**Comment by camaya** [comment]
@mattbrailsford I think is a great idea to merge the date and the datetimeview, though I'd keep the datetimeoffset separated because I think it's unique enough and the code would end up with if/else everywhere (even if it's short). I suggest moving the config object to a constant so you can inject it on both controllers.

**Comment by mattbrailsford** [comment]
Ok, I think I can get it to handle all 4 without much bother so if you want to end/disable time picking you can configure

    { picTime:true/false }

If you want to store the time as UTC time in the DB (it will display as local time to the user), you can configure

    { storeUtc:true }

And if you want to store the UTC offset for DateTimeOffset fields you can configure

    { storeUtcOffset:true }

Does this sound reasonable?

If I could find a nice way to do inheritance in angular, we could probably separate them out again and just have them inherit from the same view/controller put just configure those flags on the fly, but not quite sure how to go about that atm.

**Comment by TimGeyssens** [comment]
@mattbrailsford for me it makes sense since the different date(time) pickers use pretty much the same code, so go for it :) @camaya would it work in your case?

**Comment by mattbrailsford** [comment]
And as soon as I mention it, I find a way :)

So I can now have separate views for them all but they all just reuse the same datetime view / controller and I'll make the controller smart enough to figure out which flags to set :)

**Comment by TimGeyssens** [comment]
Awesome :)

**Comment by mattbrailsford** [comment]
Code pushed up in commit d4b78b5 so we should be able to close this down now :)
