### ISSUE TITLE
Move the rte field editor standard buttons to config file

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#60]
Currently it's hardcoded in the controller, would be nice if it's easy to change 

'preview', '|', 'undo', 'redo', '|', 'copy', 'cut', 'paste', '|', 'bold', 'italic', '|', 'link', 'unlink'

**Comment by TimGeyssens** [comment]
Also make it easy for custom editors to read from the config, providing a config resource

**Comment by mattbrailsford** [comment]
Why would other editors need to access it? I say keep it internal / restricted till someone requests it, that way you don't end up supporting too many edge cases

**Comment by TimGeyssens** [comment]
Yeah true, not needed

**Comment by TimGeyssens** [comment]
So they are added as server variables, simply add settings to the config with a key and you are able to fetch them with Umbraco.Sys.ServerVariables.uioMatic.settings.key
