### ISSUE TITLE
Add a formatted string list view view

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#61]
Config option would be the format

**Comment by mattbrailsford** [comment]
Wonder if this could be a config option on the label view rather than a
whole new view?

**Comment by TimGeyssens** [comment]
Ah yes even better :)

**Comment by mattbrailsford** [comment]
What kind of things are we wanting to do with formatting? Just format the value like a currency or something? or are you wanting to be able to access other property values and merge them?

**Comment by TimGeyssens** [comment]
My idea was to allow it to format like a currency or a date in a specific format

**Comment by mattbrailsford** [comment]
Perfect! The easier one :)

**Comment by TimGeyssens** [comment]
Would be cool if it also supports custom filters so you could write one for a timestamp that would use moment and would say 17 minutes ago

**Comment by mattbrailsford** [comment]
Hmm, I might just let it support angular filters then so you could do "value|mytimefilter" and it would apply the angular filter to the value. That way you could write filters for anything.

**Comment by TimGeyssens** [comment]
Yup think that makes sense
