### ISSUE TITLE
Should we move the create button to the top right

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#66]
To follow the Umbraco convention, would also allow us to plug in additional actions (of course it would only be a single button in case you don't have additional actions)

![Image of Content Editor](https://s12.postimg.org/m2gboc97h/Screen_Shot_2016_10_26_at_16_10_50.png)

**Comment by mattbrailsford** [comment]
Are you referring to the list view? If so, umbraco still has the create button above the grid top left no? That "actions" box is usually to do with complimentary actions. Might be a good away to have third parties provide custom actions though, like "export as csv" or "import from xyz"?

**Comment by TimGeyssens** [comment]
Yup would be a good location for that

**Comment by TimGeyssens** [comment]
Leaving create where it is, this location is now used for List Actions
