### ISSUE TITLE
Convert template fields to use angular syntax

### ISSUE THREAD

**Issue by mattbrailsford** [TimGeyssens/UIOMatic#67]
There are places we ask people to provide a template for a label which is usually in the format

    Field1 + " " + Field2

We should change it to support angular syntax

    {{Field1}} {{Field2}}

**Comment by TimGeyssens** [comment]
Good idea and consistent with some other packages so 👍

**Comment by mattbrailsford** [comment]
Done as part of commit 12443f33c9a4482e6e05d655a82a9c11290785f6
