### ISSUE TITLE
Check the paging controls on the list view

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#68]
If I remember correct they could use some TLC when you have a lot of pages

**Comment by TimGeyssens** [comment]
Yup since now it is just one long list 

![](http://s14.postimg.org/am42uirdt/Screen_Shot_2016_10_27_at_11_52_33.png)

**Comment by mattbrailsford** [comment]
Copied the pagination control from core which should sort this.

Could do with figuring out how we can apply some conditional styles though as the styles in older versions of umbraco are way different and those newer bulky pagination controls look odd in the grey tfoot. Could do with removing the grey background if on the newer styles, but no idea how you'd check for that.

**Comment by mattbrailsford** [comment]
Ok, copied Warrens version comparison utility service from here https://t.co/2d489evZVT and am now checking which version of the pagination control to use so the UI fits better.
