### ISSUE TITLE
Easier way to create static lists

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#71]
Currently you have to create a custom field editor

https://our.umbraco.org/projects/developer-tools/ui-o-matic/computer-says-no/77820-static-drop-down-list

**Comment by TimGeyssens** [comment]
THis would be ideal I think [UIOMaticField(View = UIOMatic.Constants.FieldEditors.RadioButtonList, Config = "{'prevalues':'a,b,c'}")]

So config with prevalues or config with another type

**Comment by mattbrailsford** [comment]
My only concern is that it starts to make the attributes config really bulky. Technically all of this is possible anyway, it just takes someone to write it, but I kinda like the separate view option as it's much easier to read in a separate file.

**Comment by TimGeyssens** [comment]
Yeah haven't thought it trough but indeed if you have lots of prevalues the attribute will become massive
