### ISSUE TITLE
List Actions need some UI TLC

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#72]
Button doesn't seem to be at correct place, and maybe add an icon for each action?

**Comment by TimGeyssens** [comment]
Updated in commit  https://github.com/TimGeyssens/UIOMatic/commit/7958015695a34eecbd2cf0b7d4953b3586012dee

**Comment by mattbrailsford** [comment]
Might want to look at making the menu right align with the button. And maybe look at moving the styles to the UIOMatic stylesheet rather than being inline. 

![capture](https://cloud.githubusercontent.com/assets/527305/19804357/bb177e9c-9d05-11e6-8fc2-029c52a80040.PNG)

**Comment by TimGeyssens** [comment]
Ah well spotted, yeah will give that a go

**Comment by TimGeyssens** [comment]
@mattbrailsford any objections in releasing an RC today? Just doing some final UI tweaks but unless you where still planning on doing something I think we are good :)

**Comment by mattbrailsford** [comment]
Nope, I'm happy with that. I did some biggish changes last night/this morning, but don't think there is anything fundamental that needs doing now for v2, so yea, go for it.

**Comment by TimGeyssens** [comment]
Added another issue to take an overall look at inline css https://github.com/TimGeyssens/UIOMatic/issues/73 so closing this one
