### ISSUE TITLE
Should we add something to the dashboard? 

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#74]
Since it is so empty atm but not sure what makes sense

**Comment by mattbrailsford** [comment]
I was thinking a welcome dashboard for a moment then, but the problem is, that would likely be "developer" focused, but you'd want something "client" focused really.

What that is though I'm not entirely sure. Quite difficult when everything within it is all dynamic so you don't know what is going to exist.

Maybe we could add a property on UIOMatic that says IncludeInDashboard or something, then maybe have a summary dashboard for those entities. Little panels with big numbers showing total number of records or something?

**Comment by mattbrailsford** [comment]
Just something like this taken from Wagtail CMS 

![image](https://cloud.githubusercontent.com/assets/527305/19810367/1365ff8c-9d25-11e6-9e09-c1275eff96db.png)

**Comment by TimGeyssens** [comment]
Ah yeah good idea :)

**Comment by mattbrailsford** [comment]
I don't think we really record any other "stats" for us to be able to report really do we? I think they could work ok though. Probably just add a new method to the Repository interface for GetTotalRecords or something and call that. Should be pretty simple :) I don't mind taking a look if you'd like it for 2.0?

**Comment by TimGeyssens** [comment]
Yeah if you got time go for it :)

**Comment by mattbrailsford** [comment]
All done! :) 
![capture](https://cloud.githubusercontent.com/assets/527305/19817493/ac75af74-9d43-11e6-9f08-fa203c1e61d3.PNG)

**Comment by mattbrailsford** [comment]
Clicking the cells take you to the create screen for that entity type. Thought that made most sense. Could link to the container node, but that only makes sense if it's a list view. Unless we make it link to the list if it's a list view, and create if it's not, but then would that get confusing?

**Comment by TimGeyssens** [comment]
Wow that was quick :) hmm yeah I see what you are getting at think create is fine for the time being we'll see if we get any feedback on that once it's in use by folks

**Comment by TimGeyssens** [comment]
Ow and what if you set the model to be readonly then I suppose it should direct you to the list view... and in case of tree render do nothing in that case I suppose

**Comment by mattbrailsford** [comment]
Oooh, forgot about readonly, hmm, I guess I'll just make those not link for now?

**Comment by TimGeyssens** [comment]
Yeah sure :)

**Comment by mattbrailsford** [comment]
Sorted! Doesn't link, and doesn't have a rollover effect if it's readonly :) (Get's a blue border if it's linkable)

**Comment by TimGeyssens** [comment]
Awesome :)

**Comment by TimGeyssens** [comment]
I would say time to celebrate with a beer 🍻  have a great weekend!

**Comment by mattbrailsford** [comment]
Likewise. Have a good one :)
