### ISSUE TITLE
Define an object as a child of another object

### ISSUE THREAD

**Issue by skttl** [TimGeyssens/UIOMatic#75]
Lets say I have a structure like:

Family
- Id
- Name
- Address

Person
- Id
- FamilyId
- Name
- Age

I would then like to have [Person] listed as children of [Family[@Id = FamilyId]], in a list view or in the tree.

Persons should not have their own tree then, but only exist as children of families.

That would be a great feature :)

**Comment by mattbrailsford** [comment]
You should be able to use a list field view on your parent model, then set
HideFromTree on your child model to hide it from the tree.

Not at computer to give solid example, but hopefully that'll get you
started.

Disclaimer, I've not tried this, but it should work :)

**Comment by skttl** [comment]
Found something in the docs, and have tried to implement
[UIOMaticField(Name = "Family", View = "dropdown", Config = "{'typeName': 'MyWebsite.Core.Models.Family, MyWebsite.Core', 'valueColumn': 'Id', 'sortColumn': 'Name', 'textTemplate': 'Name' }")]

but I keep getting an error at UIOMaticTypeByAlias

**Comment by TimGeyssens** [comment]
@skttl yeah the docs need updating, that's the old config from v1, it has been updated slightly for v2, so typeName should be typeAlias and the textTemplate is also different

**Comment by TimGeyssens** [comment]
The following should work 

```
[UIOMaticField(View = UIOMatic.Constants.FieldEditors.Dropdown,
            Config = "{'typeAlias': 'families', 'valueColumn': 'Id', 'sortColumn': 'Name', 'textTemplate': '{{Name}}' }")]
```

Just make sure your alias is correct (so it must match the alias you gave the Families model)

**Comment by TimGeyssens** [comment]
This should be it:


```
using System.ComponentModel.DataAnnotations;
using UIOMatic.Attributes;
using Umbraco.Core.Persistence;
using Umbraco.Core.Persistence.DatabaseAnnotations;

namespace TestUIOMaticDashboard.Models
{
    [TableName("persons")]
    [PrimaryKey("Id", autoIncrement = true)]
    [UIOMatic("persons", "Persons", "Person",
      FolderIcon = "icon-users",
      ItemIcon = "icon-user",
      HideFromTree = true)]
    public class Person
    {
        [PrimaryKeyColumn(AutoIncrement = true)]
        public int Id { get; set; }


        [Required]
        [UIOMaticField(View = UIOMatic.Constants.FieldEditors.Dropdown,
            Config = "{'typeAlias': 'families', 'valueColumn': 'Id', 'sortColumn': 'Name', 'textTemplate': '{{Name}}' }")]
        public int FamilyId { get; set; }

        [Required]
        [UIOMaticField]
        [UIOMaticListViewField]
        public string Name { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
```
```
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using UIOMatic.Attributes;
using Umbraco.Core.Persistence;
using Umbraco.Core.Persistence.DatabaseAnnotations;

namespace TestUIOMaticDashboard.Models
{
    [TableName("families")]
    [PrimaryKey("Id", autoIncrement = true)]
    [UIOMatic("families", "Families", "Family",
       FolderIcon = "icon-users",
       ItemIcon = "icon-user")]
    public class Family
    {
        [PrimaryKeyColumn(AutoIncrement = true)]
        public int Id { get; set; }

        [Required]
        [UIOMaticField]
        public string Name { get; set; }

        [Required]
        [UIOMaticField(View = UIOMatic.Constants.FieldEditors.Textarea)]
        public string Address { get; set; }

        [Ignore]
        [UIOMaticField(View = UIOMatic.Constants.FieldEditors.List,
            Config = "{'typeAlias': 'persons', 'foreignKeyColumn' : 'FamilyId', 'canEdit' : true}")]
        public IEnumerable<Person> Persons { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
```


Results in the following ui
![](https://s16.postimg.org/m7rfjxued/Screen_Shot_2016_10_29_at_07_58_03.png)
but found a small bug, the hide from tree bool isn't respected

**Comment by TimGeyssens** [comment]
Ow and if you set the rendertype of persons to List you should be able to return to the family when you create a new person from the list editor

**Comment by TimGeyssens** [comment]
Docs should now be correct http://uiomatic.readthedocs.io/en/stable/

**Comment by mattbrailsford** [comment]
@TimGeyssens I've added some code to make the "return to list" button show, even if the render type is tree, but you've come from a list field view.

**Comment by TimGeyssens** [comment]
Nice 👍
