### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by lars-erik** [TimGeyssens/UIOMatic#77]
It would be really nice if it was possible to group entities in different sections. A section could have a custom dashboard, and you'd only have the relevant objects in the menu. Would help scaffold different subsystems.

**Comment by mattbrailsford** [comment]
Should be pretty easy to put a TreeAlias on UIOMaticAttribute and have the
tree check it against its own alias.

**Comment by mattbrailsford** [comment]
Actually, will be a tad more involved as will need to know section/tree in
order to generate correct urls where they are hardcover to move around (the
we should be able to know the section from the tree config)

**Comment by mattbrailsford** [comment]
- [ ] Add `TreeAlias` property to `UIOMaticAttribute`
- [ ] Add `TreeBaseUrl` property to 'UIOMaticTypeInfo`
- [ ] Update `PetaPocoObjectService` to populate the `TreeBaseUrl` property in the format '#/sectionAlias/treeAlias', gathering the section alias from the core umbraco trees collection
- [ ] Update all Angular Views with hardcoded URL's, substituting the base URL with the new `TreeBaseUrl` property

**Comment by TimGeyssens** [comment]
Think this was part of pull request #151 , right @ProworksDevTeam ?

**Comment by benjaminc** [comment]
If I'm understanding the issue right, yes, this should be possible now.

**Comment by TimGeyssens** [comment]
@benjaminc ace!
