### ISSUE TITLE
New issue created from UI-O-Matic

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/UIOMatic#79]
I :heart: Matt Brailsford

**Comment by TimGeyssens** [comment]
This rocks 👍

**Comment by mattbrailsford** [comment]
Haha 😂

**Comment by mattbrailsford** [comment]
You hooked uiomatic to github by any chance? 😁

**Comment by TimGeyssens** [comment]
I did :) just recording a quick vid will pop on twitter in a bit :)
