### ISSUE TITLE
Replace static "Object List" and "Object Creator" with names of objects?

### ISSUE THREAD

**Issue by tomfulton** [TimGeyssens/UIOMatic#8]
Hey Tim!  Just an idea  - when creating or editing an object, some static text is shown in the header:

![image](https://cloud.githubusercontent.com/assets/1396376/10505172/48309f56-72bf-11e5-8305-2ffb169a5dfb.png)

![image](https://cloud.githubusercontent.com/assets/1396376/10505174/50577f6a-72bf-11e5-900a-944f3bb7232b.png)

I think it might be nice for editors to see the name of the object type they're working with, like so:

![image](https://cloud.githubusercontent.com/assets/1396376/10505208/e01aab86-72bf-11e5-8a88-79ccabfb8a42.png)

![image](https://cloud.githubusercontent.com/assets/1396376/10505198/a7993d7c-72bf-11e5-9b9f-ba2b41b5c9eb.png)

I'm not sure the best way to do this though.  There is a name defined in the [`UIOMaticAttribute`](https://github.com/TimGeyssens/UIOMatic/blob/master/src/Example/Models/Dog.cs#L11), but it's plural.  Not sure if it makes sense to work with that, or add another property, for the object name or header text?

I also wonder if it makes sense to think about making the header a textbox with the name of the object, like Umbraco's edit screen does.  Ex:
![image](https://cloud.githubusercontent.com/assets/1396376/10505397/e5aa9e1a-72c1-11e5-878e-cc5d87932880.png)

**Comment by TimGeyssens** [comment]
Yeah would also love to get rid of the static texts, could use the class name...

Textbox to edit the name of the object would be ace to make it even more consistent but not sure how easy/hard it would be to make it work since currently the name of the object is coming form the ToString method and can be a combination of multiple properties

**Comment by tomfulton** [comment]
Class name works well until it's two words ;)

Yeah, I was thinking about how to get the Name field myself.  Maybe the developer should specify which property to use as the Name field in the `UIOMatic` attribute?  Something like `NameProperty:  "Name"`?  We could also use that to decide which column is linkable in the list view

**Comment by TimGeyssens** [comment]
Yeah makes sense to do it that way :+1:

**Comment by tomfulton** [comment]
Whoops - sorry for the delay :)

I just sent over a pull request that adds Umbraco-style editing of the object name, denoted by applying `[UIOMaticNameField]` to the deisred property.  It's optional in case your object doesn't have a "name".

This solves the second part of what we talked about, but there are still some cases where the static text will show.  For example, the List View still shows "Object List".  Also, if you don't specify a Name field, the Create/Edit views will still show the static text.

Any thoughts on the best way to solve this part?  Feels a bit weird, but maybe we could add a `NameSingular` property to the `UIOMaticAttribute`?  Or `EditHeaderText`, `CreateHeaderText`, and `ListHeaderText`?

**Comment by TimGeyssens** [comment]
Love the UIOMaticNameField one, great work! Yeah not sure yet on the other bit, will give it some thought

**Comment by tomfulton** [comment]
Thanks Tim!  I'll think on it as well, not really a big deal for now.

For the header of the List View, maybe we can just use the `Name` property from the `UIOMaticAttribute` since it looks like that's intended to be plural:
![list-uiomaticname](https://cloud.githubusercontent.com/assets/1396376/10984934/00de8720-83d2-11e5-94a3-448c969e8756.png)

Still not sure what to do for the Edit/Create screens since we don't have a singular version of the object type :)

**Comment by barryokane** [comment]
Hi guys,

I'm getting the error below in the console when I try to use UIOMaticNameField

    TypeError: Cannot read property 'filter' of undefined
    at Object.<anonymous> (edit.controller.js?cdv=1444393501:180)
    at e (angular.min.js?cdv=1444393501:70)
    at Da.| (angular.min.js?cdv=1444393501:140)
    at t.constant (angular.min.js?cdv=1444393501:69)
    at Da.| (angular.min.js?cdv=1444393501:140)
    at t.constant (angular.min.js?cdv=1444393501:69)
    at Object.<anonymous> (angular.min.js?cdv=1444393501:89)
    at Object.e.$digest (angular.min.js?cdv=1444393501:90)
    at Object.e.$apply (angular.min.js?cdv=1444393501:92)
    at j (angular.min.js?cdv=1444393501:101)

My class looks like this:
   
    [UIOMaticAttribute("TableName", "icon-notepad", "icon-notepad")]
    [TableName("TableName")]
    [PrimaryKey("Id", autoIncrement = true)]
    [ExplicitColumns]
    public class TableName : IUIOMaticModel
    {

        [UIOMaticIgnoreField]
        [Column("id")]
        [PrimaryKeyColumn(AutoIncrement = true)]
        public int Id { get; set; }
        
        [Column("Title")]
        [UIOMaticNameField]
        [UIOMaticField("Title", "Enter the title")]
        public string Title { get; set; }
        
        
        public IEnumerable<Exception> Validate()
        {
            var exs = new List<Exception>();

            return exs;
        }
        public override string ToString()
        {
            return "TEST: " + " (" + Title + ")";
        }
    }

A bug?  Or am I doing something wrong?

Thanks,
Barry

**Comment by TimGeyssens** [comment]
Looks like a bug, seems like it's also happening in our example project.

**Comment by TimGeyssens** [comment]
But it does seem to function even with the js error..., does it work in your case @barryokane ? Or does it fail as soon as the error pops up?

**Comment by barryokane** [comment]
It didn't seem to affect the functionality, but I took out the attribute as it was making my debugging of other stuff confusing :)

Otherwise the package is working really well for me. +1

**Comment by TimGeyssens** [comment]
Great :) well we'll look into the error

**Comment by TimGeyssens** [comment]
@tomfulton any ideas on how to fix the bug? Haven't look that much into detail on the attribute so would be ace if you could take a look :)

**Comment by tomfulton** [comment]
Hi - I think this was caused by the `filter` getting executed before `$scope.properties` is ready.  I added a null check in #15 and it looks good now :+1:

**Comment by TimGeyssens** [comment]
Sweet, thanks :)

**Comment by TimGeyssens** [comment]
Possible in v2
