### ISSUE TITLE
Dont show data, but knows how many rows I have

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic#81]
Hi,

Just installed this package! =)

I already have the section, items and summary page.

I have "Contacts" and "Comments". UIOMatic know how many rows I have. The summary page knows the Total Items.

In the list page (RenderType = UIOMaticRenderType.List) it appears blank.

The "delete" button works.
![image](https://cloud.githubusercontent.com/assets/10515084/19936939/3a7dda54-a117-11e6-92df-00b6b081965a.png)

**Comment by pedroadaodev** [comment]
using UIOMatic.Attributes;
using UIOMatic.Enums;
using Umbraco.Core.Persistence;
using Umbraco.Core.Persistence.DatabaseAnnotations;

namespace MyProject.FrontEnd.Models
{
    [UIOMatic("contact", "Contact", "Contact", FolderIcon = "icon-users", ItemIcon = "icon-user", RenderType = UIOMaticRenderType.List, ShowOnSummaryDashboard = true)]
    [TableName("Contacts")]
    public class ContactsBoModel
    {
        [PrimaryKeyColumn(AutoIncrement = true)]
        public int Id { get; set; }

```
    public int NodeId { get; set; }

    public string LanguageIso { get; set; }

    [UIOMaticField(Name = "Name", Description = "Enter name")]
    public string Name { get; set; }

    [UIOMaticField(Name = "Email", Description = "Enter email")]
    public string Email { get; set; }

    public string Country { get; set; }
}
```

}

**Comment by mattbrailsford** [comment]
You need to add some [UIOMaticListViewField] attributes to the properties you want to display in the list view, otherwise UI-O-Matic doesn't know what you want to display.

**Comment by mattbrailsford** [comment]
Check out the docs for the list view here http://uiomatic.readthedocs.io/en/stable/04.Listview/

**Comment by pedroadaodev** [comment]
Yes!!! @mattbrailsford  Thank you so much! =)

THIS IS SOOOOOO GREAT!!!! =)

**Comment by mattbrailsford** [comment]
No problem :)

Closing the issue down.
