### ISSUE TITLE
How to - Dashboard click and go to list view

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic#82]
Hi,

On the dashboard I can click on a "Object" and go to create view. Is there a option to go to list view?

Thanks,
Pedro

**Comment by mattbrailsford** [comment]
Not currently no. We thought it might be confusing if list view models went
to the list, and tree based models went to create (because trees dont have
any other view), so we opted for going to create.

Would like to know what others think though.

**Comment by TimGeyssens** [comment]
Maybe a hover state that shows 2 options when it's rendered as list (create and view data) and only 1 option when it's tree (create)

**Comment by mattbrailsford** [comment]
Mocked this up last night, but not sure if I'm overly happy with it really

![capture](https://cloud.githubusercontent.com/assets/527305/19962598/62460950-a1b0-11e6-8d7d-b2a214ffc3ff.PNG)

**Comment by pedroadaodev** [comment]
I love it! =)

View or List?

**Comment by TimGeyssens** [comment]
I like it but your call :)

**Comment by akeilox** [comment]
how about showing the view/create option inline, ie. next line after the total ?
the icon/font can be resized to accommodate and one less click for end user.

**Comment by TimGeyssens** [comment]
@akeilox yeah good idea :)

**Comment by mattbrailsford** [comment]
Another option, but again, still not 100% on this one

![ui2](https://cloud.githubusercontent.com/assets/527305/19971118/083255ba-a1d6-11e6-8ca3-1534d93a11e9.png)

(Would show on hover)

**Comment by TimGeyssens** [comment]
Nice :)

**Comment by akeilox** [comment]
Looks great!

**Comment by pedroadaodev** [comment]
WOW! Even better! =)

**Comment by pedroadaodev** [comment]
Hi,

I upgraded but I cannot see the "new buttons". So I need to do something?

Best regards,
Pedro

**Comment by TimGeyssens** [comment]
Hey @pedroadaodev , it will be available in 2.0.2 maintenance release sheduled for Thursday so I assume you upgraded to 2.0.1 ? And that release doesn't have this new UI...

**Comment by pedroadaodev** [comment]
that's it. I have 2.0.1.

Can't wait for Thursday. Thank you guys! =)

**Comment by TimGeyssens** [comment]
No problem :) and in the meantime if you encounter any bugs are have any more suggestions make sure to shoot them on the issue tracker! Thanks!

**Comment by mrpeo** [comment]
I'm using UIOMatic 2.0.3,
The sumary not show anything. See screenshots.

Please help. Thank you very much.

![theclass](https://cloud.githubusercontent.com/assets/4709861/24351695/f4469d84-1310-11e7-8f4d-8b5e2b48fe15.jpg)
![dashboard](https://cloud.githubusercontent.com/assets/4709861/24351765/3d617bd8-1311-11e7-81a7-cd78f45a1d20.jpg)

**Comment by pedroadaodev** [comment]
Hi @mrpeo 

I think you are missing this
ShowOnSummaryDashboard = true, 

[UIOMatic(
       "people", 
       "People", 
       ...
        ShowOnSummaryDashboard = true, 
]

**Comment by mrpeo** [comment]
Work like a charm.

Thanks @pedroadaodev
