### ISSUE TITLE
Update DLL version to 2.0.0 in Assembly Information

### ISSUE THREAD

**Issue by khmjcd** [TimGeyssens/UIOMatic#83]
![2016-11-03_11h36_12](https://cloud.githubusercontent.com/assets/11330055/19962829/cd727b42-a1b9-11e6-8418-9ba9742291ed.png)

**Comment by mattbrailsford** [comment]
This should have been set via the build script, we'll need to check why it wasn't

**Comment by TimGeyssens** [comment]
Fixed in upcoming release 
![image](https://user-images.githubusercontent.com/2988648/85071461-d0e4ab80-b1b7-11ea-98aa-a73dbddb27e6.png)
