### ISSUE TITLE
new feature - List Field Views - Content

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic#85]
Hi,

Here we could have a field to display Node.Name with link to content in umbraco content editor
http://uiomatic.readthedocs.io/en/stable/05.ListFieldViews/#default

[UIOMaticField(Name = "Node", Description = "Select Language Node", View = UIOMatic.Constants.FieldEditors.PickerContent)]
[UIOMaticListViewField(View = **UIOMatic.Constants.FieldViews.FieldEditors.Content**)]
public int NodeId { get; set; }

old:
![image](https://cloud.githubusercontent.com/assets/10515084/19971865/3b71de9e-a1d8-11e6-90a2-cb3b1483c951.png)

new:
![image](https://cloud.githubusercontent.com/assets/10515084/19971958/8e09872e-a1d8-11e6-9849-3dd2f233fdf6.png)

Thank you,
Pedro

**Comment by TimGeyssens** [comment]
That's already possible :)

Try adding a new property

```
[Ignore]
[UIOMaticListViewField]
public string NodeName { 
   get
   {
     if(this.NodeId == 0) return string.Empty;
     return //logic to get node name by id
   }
}
```

**Comment by TimGeyssens** [comment]
And then don't show the NodeId in the listview... make sense?

**Comment by pedroadaodev** [comment]
Thank you! =)

**Comment by TimGeyssens** [comment]
No prob, hope you find the package useful :)

**Comment by pedroadaodev** [comment]
Yes! I love this package! =)
