### ISSUE TITLE
Naviagation enhancement between views

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic#86]
Hi,

When I'm in a list view, click to edit an item. Then I click "return to list" I loose my pagination, filter, sort field, etc.

Is it possible keep my navigation?

Thanks,
Pedro

**Comment by TimGeyssens** [comment]
Currently not but would be a great enhancement :)

**Comment by mistyn8** [comment]
would be nice for "return to list" to become "return to XXXX" XXX being the parent name?
maybe also a breadcrumb for if you are 3 or so lists deep? :-)

**Comment by Killerkiwi2005** [comment]
I have this some where we stashed in localstorage.... I'll see if I can dig it out

**Comment by Killerkiwi2005** [comment]
Found it I don't have time to do a pull request atm but here's the basics from our v2 code if some one wants to complete it

https://nopaste.xyz/?d1fe67a01fd22b60#68kwMJMxW4VPFuxfZaxj21Bcx2G1hRR1RLGKQ8qKcVGZ

Note you could maybe change it to sessionStorage instead so its not saved long term

**Comment by TimGeyssens** [comment]
@Killerkiwi2005 super will take a look, thanks for sharing

**Comment by TimGeyssens** [comment]
Part of 3.0.14 :) thanks @Killerkiwi2005

**Comment by pedroadaodev** [comment]
Thank you all!! 👍
