### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by richardterris** [TimGeyssens/UIOMatic#87]
It might be a nice feature to make the dashboard text editable, and/or hidden when a class is marked as read-only. As it stands a read-only class will still show 'update [your item name]'

Also, could add the ability to change the text on the section button, so that it doesn't need to say Uiomatic, or at least you could have '[your custom text](UIOmatic)' 

Just suggestions - this is a fantastic package!

**Comment by mattbrailsford** [comment]
Good call on the first issue.

Second issue should get covered by another open issue (away from pc and
can't recall issue number atm) so will just deem that as a separate issue
for now.

Thanks for reporting

**Comment by TimGeyssens** [comment]
Yup think @mattbrailsford is referring to issue #77
