### ISSUE TITLE
List View - Pagination error

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic#89]
Hi,

If you have a PETA class with this
[UIOMatic("newsletter", "Newsletters", "Newsletter", 
        RenderType = UIOMaticRenderType.List,
        SortColumn = "Id",
        SortOrder = "desc"
]

When you go to page "2" the sort order is "Id ASC".

Pedro

**Comment by TimGeyssens** [comment]
Thanks for reporting, hope to fix this for Fridays release!

**Comment by TimGeyssens** [comment]
Just been able to reproduce the bug, looking into a fix now :)

**Comment by pedroadaodev** [comment]
UAU thank you!!  😁🙋
