### ISSUE TITLE
Create new Custom Property Views

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic#95]
I'm creating a new custom property view.

Add the code in this page.
http://uiomatic.readthedocs.io/en/latest/04.CustomPropertyViews/

I get this error on the browser console.
angular.min.js?cdv=2062270818:63 Error: Argument 'Example.Picker.Person' is not a function, got undefined
    at cb (angular.min.js?cdv=2062270818:17)
    at xa (angular.min.js?cdv=2062270818:17)
    at angular.min.js?cdv=2062270818:53
    at angular.min.js?cdv=2062270818:44
    at n (angular.min.js?cdv=2062270818:7)
    at k (angular.min.js?cdv=2062270818:44)
    at e (angular.min.js?cdv=2062270818:40)
    at angular.min.js?cdv=2062270818:39
    at angular.min.js?cdv=2062270818:158
    at angular.min.js?cdv=2062270818:100

I've double check the name, paths and it seems ok.

**Comment by TimGeyssens** [comment]
Can you post your code? Seems like you using the Example.Picker.Person as controller name , is that a controller that exists?

**Comment by pedroadaodev** [comment]
![image](https://cloud.githubusercontent.com/assets/10515084/20269550/7e2b68ee-aa7b-11e6-87df-970698c40ead.png)

contentLink.controller.js
`angular.module("umbraco").controller("Example.Picker.Person",
    function ($scope, $http) {
        console.log("pedro");
    });`

contentLink.html
`<div ng-controller="Example.Picker.Person">
    <a href="">LINK</a>
</div>`

package.manifest
`{
    javascript: [
    '~/App_Plugins/Amorim/UIOMatic/contentLink.controller.js',
    ]
}`

**Comment by TimGeyssens** [comment]
ah think your package.manifest can't be that deep, try putting it under App_Plugins/Amorium instead  of in the subfolder

**Comment by pedroadaodev** [comment]
That's it. Thank you! =)

**Comment by TimGeyssens** [comment]
No problem, glad I could help :)
