### ISSUE TITLE
DOCS - error in textarea

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic#96]
http://uiomatic.readthedocs.io/en/latest/03.DefaultPropertyViews/#textarea

`[UIOMaticField("TextArea", "Example textarea property",
    View = "checkbox")]
public string Textarea { get; set; }`

should be

`[UIOMaticField("TextArea", "Example textarea property",
    View = "textarea")]
public string Textarea { get; set; }`

some reads the docs!  =)

**Comment by TimGeyssens** [comment]
Thanks for reporting but just so you are aware those are the v1 docs, for v2 please go to http://uiomatic.readthedocs.io/en/stable/ :)
